import { CodeLanguage } from './types';

export interface LeetCodeProblem {
  id: string;
  number: number;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  category: string;
  neetcodeSection: string;
  description: string;
  inputExample: string;
  outputExample: string;
  acceptance: string;
}

export const NEETCODE_PROBLEMS: LeetCodeProblem[] = [
  {
    id: 'twosum',
    number: 1,
    title: 'Two Sum',
    difficulty: 'Easy',
    category: 'Arrays & Hashing',
    neetcodeSection: 'Arrays & Hashing',
    description: 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. You may assume that each input would have exactly one solution, and you may not use the same element twice. You can return the answer in any order.',
    inputExample: 'nums = [2, 7, 11, 15], target = 9',
    outputExample: '[0, 1]',
    acceptance: '51.3%'
  },
  {
    id: 'valid_parentheses',
    number: 20,
    title: 'Valid Parentheses',
    difficulty: 'Easy',
    category: 'Stack',
    neetcodeSection: 'Stack',
    description: 'Given a string s containing just the characters \'(\', \')\', \'{\', \'}\', \'[\' and \']\', determine if the input string is valid. An input string is valid if open brackets are closed by the same type of brackets, and open brackets are closed in the correct order.',
    inputExample: 's = "({[]})"',
    outputExample: 'true',
    acceptance: '40.8%'
  },
  {
    id: 'reverse_list',
    number: 206,
    title: 'Reverse Linked List',
    difficulty: 'Easy',
    category: 'Linked List',
    neetcodeSection: 'Linked List',
    description: 'Given the head of a singly linked list, reverse the list, and return the reversed list.',
    inputExample: 'head = [1, 2, 3, 4]',
    outputExample: '[4, 3, 2, 1]',
    acceptance: '75.2%'
  },
  {
    id: 'invert_tree',
    number: 226,
    title: 'Invert Binary Tree',
    difficulty: 'Easy',
    category: 'Trees',
    neetcodeSection: 'Trees',
    description: 'Given the root of a binary tree, invert the tree (mirror its structure swapping left and right subtrees), and return its root.',
    inputExample: 'root = [4, 2, 7, 1, 3, 6, 9]',
    outputExample: '[4, 7, 2, 9, 6, 3, 1]',
    acceptance: '76.8%'
  },
  {
    id: 'binary_search',
    number: 704,
    title: 'Binary Search',
    difficulty: 'Easy',
    category: 'Binary Search',
    neetcodeSection: 'Binary Search',
    description: 'Given an array of integers nums which is sorted in ascending order, and an integer target, write a function to search target in nums. If target exists, then return its index. Otherwise, return -1. You must write an algorithm with O(log n) runtime complexity.',
    inputExample: 'nums = [-1, 0, 3, 5, 9, 12], target = 9',
    outputExample: '4',
    acceptance: '56.9%'
  },
  {
    id: 'buy_sell_stock',
    number: 121,
    title: 'Best Time to Buy and Sell Stock',
    difficulty: 'Easy',
    category: 'Sliding Window',
    neetcodeSection: 'Sliding Window',
    description: 'You are given an array prices where prices[i] is the price of a given stock on the i-th day. You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock. Return the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.',
    inputExample: 'prices = [7, 1, 5, 3, 6, 4]',
    outputExample: '5 (Buy on day 2 @ $1, sell on day 5 @ $6)',
    acceptance: '53.6%'
  },
  {
    id: 'container_with_most_water',
    number: 11,
    title: 'Container With Most Water',
    difficulty: 'Medium',
    category: 'Two Pointers',
    neetcodeSection: 'Two Pointers',
    description: 'You are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the i-th line are (i, 0) and (i, height[i]). Find two lines that together with the x-axis form a container, such that the container contains the most water. Return the maximum amount of water a container can store.',
    inputExample: 'height = [1, 8, 6, 2, 5, 4, 8, 3, 7]',
    outputExample: '49',
    acceptance: '54.2%'
  },
  {
    id: 'group_anagrams',
    number: 49,
    title: 'Group Anagrams',
    difficulty: 'Medium',
    category: 'Arrays & Hashing',
    neetcodeSection: 'Arrays & Hashing',
    description: 'Given an array of strings strs, group the anagrams together. You can return the answer in any order.',
    inputExample: 'strs = ["eat", "tea", "tan", "ate", "nat", "bat"]',
    outputExample: '[["bat"], ["nat", "tan"], ["ate", "eat", "tea"]]',
    acceptance: '68.1%'
  },
  {
    id: 'threesum',
    number: 15,
    title: '3Sum',
    difficulty: 'Medium',
    category: 'Two Pointers',
    neetcodeSection: 'Two Pointers',
    description: 'Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.',
    inputExample: 'nums = [-1, 0, 1, 2, -1, -4]',
    outputExample: '[[-1, -1, 2], [-1, 0, 1]]',
    acceptance: '34.7%'
  },
  {
    id: 'longest_substring',
    number: 3,
    title: 'Longest Substring Without Repeating Characters',
    difficulty: 'Medium',
    category: 'Sliding Window',
    neetcodeSection: 'Sliding Window',
    description: 'Given a string s, find the length of the longest substring without repeating characters.',
    inputExample: 's = "abcabcbb"',
    outputExample: '3 (The substring is "abc")',
    acceptance: '34.6%'
  },
  {
    id: 'merge_two_lists',
    number: 21,
    title: 'Merge Two Sorted Lists',
    difficulty: 'Easy',
    category: 'Linked List',
    neetcodeSection: 'Linked List',
    description: 'You are given the heads of two sorted linked lists list1 and list2. Merge the two lists into one sorted list and return its head.',
    inputExample: 'list1 = [1, 2, 4], list2 = [1, 3, 4]',
    outputExample: '[1, 1, 2, 3, 4, 4]',
    acceptance: '64.3%'
  }
];

export interface CodeLine {
  text: string;
  indent: number;
}

export type LeetSnippetsRegistry = Record<
  string, // problem ID
  Record<CodeLanguage, CodeLine[]>
>;

export const LEETCODE_CODE_SNIPPETS: LeetSnippetsRegistry = {
  twosum: {
    javascript: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'function twoSum(nums, target) {', indent: 0 },
      { text: '  let map = new Map();', indent: 1 },
      { text: '  for (let i = 0; i < nums.length; i++) {', indent: 1 },
      { text: '    let complement = target - nums[i];', indent: 2 },
      { text: '    if (map.has(complement)) {', indent: 2 },
      { text: '      return [map.get(complement), i];', indent: 3 },
      { text: '    }', indent: 2 },
      { text: '    map.set(nums[i], i);', indent: 2 },
      { text: '  }', indent: 1 },
      { text: '  return [];', indent: 1 },
      { text: '}', indent: 0 }
    ],
    python: [
      { text: '# Placeholder spacer', indent: 0 },
      { text: 'def twoSum(nums, target):', indent: 0 },
      { text: '    num_to_index = {}', indent: 1 },
      { text: '    for i, num in enumerate(nums):', indent: 1 },
      { text: '        complement = target - num', indent: 2 },
      { text: '        if complement in num_to_index:', indent: 2 },
      { text: '            return [num_to_index[complement], i]', indent: 3 },
      { text: '        # endif', indent: 2 },
      { text: '        num_to_index[num] = i', indent: 2 },
      { text: '    # endfor', indent: 1 },
      { text: '    return []', indent: 1 },
      { text: '# end func', indent: 0 }
    ],
    cpp: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'vector<int> twoSum(vector<int>& nums, int target) {', indent: 0 },
      { text: '    unordered_map<int, int> m;', indent: 1 },
      { text: '    for (int i = 0; i < nums.size(); ++i) {', indent: 1 },
      { text: '        int complement = target - nums[i];', indent: 2 },
      { text: '        if (m.find(complement) != m.end()) {', indent: 2 },
      { text: '            return {m[complement], i};', indent: 3 },
      { text: '        }', indent: 2 },
      { text: '        m[nums[i]] = i;', indent: 2 },
      { text: '    }', indent: 1 },
      { text: '    return {};', indent: 1 },
      { text: '}', indent: 0 }
    ],
    java: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'public int[] twoSum(int[] nums, int target) {', indent: 0 },
      { text: '    Map<Integer, Integer> map = new HashMap<>();', indent: 1 },
      { text: '    for (int i = 0; i < nums.length; i++) {', indent: 1 },
      { text: '        int complement = target - nums[i];', indent: 2 },
      { text: '        if (map.containsKey(complement)) {', indent: 2 },
      { text: '            return new int[] { map.get(complement), i };', indent: 3 },
      { text: '        }', indent: 2 },
      { text: '        map.put(nums[i], i);', indent: 2 },
      { text: '    }', indent: 1 },
      { text: '    return new int[0];', indent: 1 },
      { text: '}', indent: 0 }
    ]
  },
  valid_parentheses: {
    javascript: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'function isValid(s) {', indent: 0 },
      { text: '  let stack = [];', indent: 1 },
      { text: '  let brackets = { ")": "(", "}": "{", "]": "[" };', indent: 1 },
      { text: '  for (let char of s) {', indent: 1 },
      { text: '    if (char === "(" || char === "{" || char === "[") {', indent: 2 },
      { text: '      stack.push(char);', indent: 3 },
      { text: '    } else {', indent: 2 },
      { text: '      let top = stack.pop();', indent: 3 },
      { text: '      if (top !== brackets[char]) {', indent: 3 },
      { text: '        return false;', indent: 4 },
      { text: '      }', indent: 3 },
      { text: '    }', indent: 2 },
      { text: '  }', indent: 1 },
      { text: '  return stack.length === 0;', indent: 1 },
      { text: '}', indent: 0 }
    ],
    python: [
      { text: '# Placeholder spacer', indent: 0 },
      { text: 'def isValid(s: str) -> bool:', indent: 0 },
      { text: '    stack = []', indent: 1 },
      { text: '    brackets = {")": "(", "}": "{", "]": "["}', indent: 1 },
      { text: '    for char in s:', indent: 1 },
      { text: '        if char in brackets.values():', indent: 2 },
      { text: '            stack.append(char)', indent: 3 },
      { text: '        else:', indent: 2 },
      { text: '            if not stack or stack.pop() != brackets[char]:', indent: 3 },
      { text: '                return False', indent: 4 },
      { text: '            # endif', indent: 3 },
      { text: '        # endif', indent: 2 },
      { text: '    # endfor', indent: 1 },
      { text: '    return len(stack) == 0', indent: 1 },
      { text: '# end func', indent: 0 }
    ],
    cpp: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'bool isValid(string s) {', indent: 0 },
      { text: '    stack<char> st;', indent: 1 },
      { text: '    unordered_map<char, char> brackets = {{\')\', \'(\'}, {\'}\', \'{\'}, {\']\', \'[\'}};', indent: 1 },
      { text: '    for (char c : s) {', indent: 1 },
      { text: '        if (c == \'(\' || c == \'{\' || c == \'[\') {', indent: 2 },
      { text: '            st.push(c);', indent: 3 },
      { text: '        } else {', indent: 2 },
      { text: '            if (st.empty() || st.top() != brackets[c]) {', indent: 3 },
      { text: '                return false;', indent: 4 },
      { text: '            }', indent: 3 },
      { text: '            st.pop();', indent: 3 },
      { text: '        }', indent: 2 },
      { text: '    }', indent: 1 },
      { text: '    return st.empty();', indent: 1 },
      { text: '}', indent: 0 }
    ],
    java: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'public boolean isValid(String s) {', indent: 0 },
      { text: '    Stack<Character> stack = new Stack<>();', indent: 1 },
      { text: '    for (int i = 0; i < s.length(); i++) {', indent: 1 },
      { text: '        char c = s.charAt(i);', indent: 2 },
      { text: '        if (c == \'(\' || c == \'{\' || c == \'[\') {', indent: 2 },
      { text: '            stack.push(c);', indent: 3 },
      { text: '        } else {', indent: 2 },
      { text: '            if (stack.isEmpty()) return false;', indent: 3 },
      { text: '            char top = stack.pop();', indent: 3 },
      { text: '            if (c == \')\' && top != \'(\') return false;', indent: 3 },
      { text: '            if (c == \'}\' && top != \'{\') return false;', indent: 3 },
      { text: '            if (c == \']\' && top != \'[\') return false;', indent: 3 },
      { text: '        }', indent: 2 },
      { text: '    }', indent: 1 },
      { text: '    return stack.isEmpty();', indent: 1 },
      { text: '}', indent: 0 }
    ]
  },
  reverse_list: {
    javascript: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'function reverseList(head) {', indent: 0 },
      { text: '  let prev = null;', indent: 1 },
      { text: '  let curr = head;', indent: 1 },
      { text: '  while (curr !== null) {', indent: 1 },
      { text: '    let next = curr.next;', indent: 2 },
      { text: '    curr.next = prev;', indent: 2 },
      { text: '    prev = curr;', indent: 2 },
      { text: '    curr = next;', indent: 2 },
      { text: '  }', indent: 1 },
      { text: '  return prev;', indent: 1 },
      { text: '}', indent: 0 }
    ],
    python: [
      { text: '# Placeholder spacer', indent: 0 },
      { text: 'def reverseList(head):', indent: 0 },
      { text: '    prev = None', indent: 1 },
      { text: '    curr = head', indent: 1 },
      { text: '    while curr is not None:', indent: 1 },
      { text: '        next_temp = curr.next', indent: 2 },
      { text: '        curr.next = prev', indent: 2 },
      { text: '        prev = curr', indent: 2 },
      { text: '        curr = next_temp', indent: 2 },
      { text: '    # endwhile', indent: 1 },
      { text: '    return prev', indent: 1 },
      { text: '# end func', indent: 0 }
    ],
    cpp: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'ListNode* reverseList(ListNode* head) {', indent: 0 },
      { text: '    ListNode* prev = nullptr;', indent: 1 },
      { text: '    ListNode* curr = head;', indent: 1 },
      { text: '    while (curr != nullptr) {', indent: 1 },
      { text: '        ListNode* next_temp = curr->next;', indent: 2 },
      { text: '        curr->next = prev;', indent: 2 },
      { text: '        prev = curr;', indent: 2 },
      { text: '        curr = next_temp;', indent: 2 },
      { text: '    }', indent: 1 },
      { text: '    return prev;', indent: 1 },
      { text: '}', indent: 0 }
    ],
    java: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'public ListNode reverseList(ListNode head) {', indent: 0 },
      { text: '    ListNode prev = null;', indent: 1 },
      { text: '    ListNode curr = head;', indent: 1 },
      { text: '    while (curr != null) {', indent: 1 },
      { text: '        ListNode nextTemp = curr.next;', indent: 2 },
      { text: '        curr.next = prev;', indent: 2 },
      { text: '        prev = curr;', indent: 2 },
      { text: '        curr = nextTemp;', indent: 2 },
      { text: '    }', indent: 1 },
      { text: '    return prev;', indent: 1 },
      { text: '}', indent: 0 }
    ]
  },
  invert_tree: {
    javascript: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'function invertTree(root) {', indent: 0 },
      { text: '  if (root === null) return null;', indent: 1 },
      { text: '  let temp = root.left;', indent: 1 },
      { text: '  root.left = invertTree(root.right);', indent: 1 },
      { text: '  root.right = invertTree(temp);', indent: 1 },
      { text: '  return root;', indent: 1 },
      { text: '}', indent: 0 }
    ],
    python: [
      { text: '# Placeholder spacer', indent: 0 },
      { text: 'def invertTree(root):', indent: 0 },
      { text: '    if not root: return None', indent: 1 },
      { text: '    temp = root.left', indent: 1 },
      { text: '    root.left = invertTree(root.right)', indent: 1 },
      { text: '    root.right = invertTree(temp)', indent: 1 },
      { text: '    return root', indent: 1 },
      { text: '# end func', indent: 0 }
    ],
    cpp: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'TreeNode* invertTree(TreeNode* root) {', indent: 0 },
      { text: '    if (root == nullptr) return nullptr;', indent: 1 },
      { text: '    TreeNode* temp = root->left;', indent: 1 },
      { text: '    root->left = invertTree(root->right);', indent: 1 },
      { text: '    root->right = invertTree(temp);', indent: 1 },
      { text: '    return root;', indent: 1 },
      { text: '}', indent: 0 }
    ],
    java: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'public TreeNode invertTree(TreeNode root) {', indent: 0 },
      { text: '    if (root == null) return null;', indent: 1 },
      { text: '    TreeNode temp = root.left;', indent: 1 },
      { text: '    root.left = invertTree(root.right);', indent: 1 },
      { text: '    root.right = invertTree(temp);', indent: 1 },
      { text: '    return root;', indent: 1 },
      { text: '}', indent: 0 }
    ]
  },
  binary_search: {
    javascript: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'function search(nums, target) {', indent: 0 },
      { text: '  let l = 0, r = nums.length - 1;', indent: 1 },
      { text: '  while (l <= r) {', indent: 1 },
      { text: '    let mid = Math.floor((l + r) / 2);', indent: 2 },
      { text: '    if (nums[mid] === target) {', indent: 2 },
      { text: '      return mid;', indent: 3 },
      { text: '    } else if (nums[mid] < target) {', indent: 2 },
      { text: '      l = mid + 1;', indent: 3 },
      { text: '    } else {', indent: 2 },
      { text: '      r = mid - 1;', indent: 3 },
      { text: '    }', indent: 2 },
      { text: '  }', indent: 1 },
      { text: '  return -1;', indent: 1 },
      { text: '}', indent: 0 }
    ],
    python: [
      { text: '# Placeholder spacer', indent: 0 },
      { text: 'def search(nums, target):', indent: 0 },
      { text: '    l, r = 0, len(nums) - 1', indent: 1 },
      { text: '    while l <= r:', indent: 1 },
      { text: '        mid = (l + r) // 2', indent: 2 },
      { text: '        if nums[mid] == target:', indent: 2 },
      { text: '            return mid', indent: 3 },
      { text: '        elif nums[mid] < target:', indent: 2 },
      { text: '            l = mid + 1', indent: 3 },
      { text: '        else:', indent: 2 },
      { text: '            r = mid - 1', indent: 3 },
      { text: '        # endif', indent: 2 },
      { text: '    # endwhile', indent: 1 },
      { text: '    return -1', indent: 1 },
      { text: '# end func', indent: 0 }
    ],
    cpp: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'int search(vector<int>& nums, int target) {', indent: 0 },
      { text: '    int l = 0, r = nums.size() - 1;', indent: 1 },
      { text: '    while (l <= r) {', indent: 1 },
      { text: '        int mid = l + (r - l) / 2;', indent: 2 },
      { text: '        if (nums[mid] == target) {', indent: 2 },
      { text: '            return mid;', indent: 3 },
      { text: '        } else if (nums[mid] < target) {', indent: 2 },
      { text: '            l = mid + 1;', indent: 3 },
      { text: '        } else {', indent: 2 },
      { text: '            r = mid - 1;', indent: 3 },
      { text: '        }', indent: 2 },
      { text: '    }', indent: 1 },
      { text: '    return -1;', indent: 1 },
      { text: '}', indent: 0 }
    ],
    java: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'public int search(int[] nums, int target) {', indent: 0 },
      { text: '    int l = 0, r = nums.length - 1;', indent: 1 },
      { text: '    while (l <= r) {', indent: 1 },
      { text: '        int mid = l + (r - l) / 2;', indent: 2 },
      { text: '        if (nums[mid] == target) {', indent: 2 },
      { text: '            return mid;', indent: 3 },
      { text: '        } else if (nums[mid] < target) {', indent: 2 },
      { text: '            l = mid + 1;', indent: 3 },
      { text: '        } else {', indent: 2 },
      { text: '            r = mid - 1;', indent: 3 },
      { text: '        }', indent: 2 },
      { text: '    }', indent: 1 },
      { text: '    return -1;', indent: 1 },
      { text: '}', indent: 0 }
    ]
  },
  buy_sell_stock: {
    javascript: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'function maxProfit(prices) {', indent: 0 },
      { text: '  let l = 0, r = 1;', indent: 1 },
      { text: '  let maxP = 0;', indent: 1 },
      { text: '  while (r < prices.length) {', indent: 1 },
      { text: '    if (prices[l] < prices[r]) {', indent: 2 },
      { text: '      let profit = prices[r] - prices[l];', indent: 3 },
      { text: '      maxP = Math.max(maxP, profit);', indent: 3 },
      { text: '    } else {', indent: 2 },
      { text: '      l = r;', indent: 3 },
      { text: '    }', indent: 2 },
      { text: '    r++;', indent: 2 },
      { text: '  }', indent: 1 },
      { text: '  return maxP;', indent: 1 },
      { text: '}', indent: 0 }
    ],
    python: [
      { text: '# Placeholder spacer', indent: 0 },
      { text: 'def maxProfit(prices):', indent: 0 },
      { text: '    l, r = 0, 1', indent: 1 },
      { text: '    max_p = 0', indent: 1 },
      { text: '    while r < len(prices):', indent: 1 },
      { text: '        if prices[l] < prices[r]:', indent: 2 },
      { text: '            profit = prices[r] - prices[l]', indent: 3 },
      { text: '            max_p = max(max_p, profit)', indent: 3 },
      { text: '        else:', indent: 2 },
      { text: '            l = r', indent: 3 },
      { text: '        # endif', indent: 2 },
      { text: '        r += 1', indent: 2 },
      { text: '    # endwhile', indent: 1 },
      { text: '    return max_p', indent: 1 },
      { text: '# end func', indent: 0 }
    ],
    cpp: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'int maxProfit(vector<int>& prices) {', indent: 0 },
      { text: '    int l = 0, r = 1;', indent: 1 },
      { text: '    int maxP = 0;', indent: 1 },
      { text: '    while (r < prices.size()) {', indent: 1 },
      { text: '        if (prices[l] < prices[r]) {', indent: 2 },
      { text: '            int profit = prices[r] - prices[l];', indent: 3 },
      { text: '            maxP = max(maxP, profit);', indent: 3 },
      { text: '        } else {', indent: 2 },
      { text: '            l = r;', indent: 3 },
      { text: '        }', indent: 2 },
      { text: '        r++;', indent: 2 },
      { text: '    }', indent: 1 },
      { text: '    return maxP;', indent: 1 },
      { text: '}', indent: 0 }
    ],
    java: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'public int maxProfit(int[] prices) {', indent: 0 },
      { text: '    int l = 0, r = 1;', indent: 1 },
      { text: '    int maxP = 0;', indent: 1 },
      { text: '    while (r < prices.length) {', indent: 1 },
      { text: '        if (prices[l] < prices[r]) {', indent: 2 },
      { text: '            int profit = prices[r] - prices[l];', indent: 3 },
      { text: '            maxP = Math.max(maxP, profit);', indent: 3 },
      { text: '        } else {', indent: 2 },
      { text: '            l = r;', indent: 3 },
      { text: '        }', indent: 2 },
      { text: '        r++;', indent: 2 },
      { text: '    }', indent: 1 },
      { text: '    return maxP;', indent: 1 },
      { text: '}', indent: 0 }
    ]
  },
  container_with_most_water: {
    javascript: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'function maxArea(height) {', indent: 0 },
      { text: '  let l = 0, r = height.length - 1;', indent: 1 },
      { text: '  let maxA = 0;', indent: 1 },
      { text: '  while (l < r) {', indent: 1 },
      { text: '    let area = Math.min(height[l], height[r]) * (r - l);', indent: 2 },
      { text: '    maxA = Math.max(maxA, area);', indent: 2 },
      { text: '    if (height[l] < height[r]) {', indent: 2 },
      { text: '      l++;', indent: 3 },
      { text: '    } else {', indent: 2 },
      { text: '      r--;', indent: 3 },
      { text: '    }', indent: 2 },
      { text: '  }', indent: 1 },
      { text: '  return maxA;', indent: 1 },
      { text: '}', indent: 0 }
    ],
    python: [
      { text: '# Placeholder spacer', indent: 0 },
      { text: 'def maxArea(height):', indent: 0 },
      { text: '    l, r = 0, len(height) - 1', indent: 1 },
      { text: '    max_a = 0', indent: 1 },
      { text: '    while l < r:', indent: 1 },
      { text: '        area = min(height[l], height[r]) * (r - l)', indent: 2 },
      { text: '        max_a = max(max_a, area)', indent: 2 },
      { text: '        if height[l] < height[r]:', indent: 2 },
      { text: '            l += 1', indent: 3 },
      { text: '        else:', indent: 2 },
      { text: '            r -= 1', indent: 3 },
      { text: '        # endif', indent: 2 },
      { text: '    # endwhile', indent: 1 },
      { text: '    return max_a', indent: 1 },
      { text: '# end func', indent: 0 }
    ],
    cpp: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'int maxArea(vector<int>& height) {', indent: 0 },
      { text: '    int l = 0, r = height.size() - 1;', indent: 1 },
      { text: '    int maxA = 0;', indent: 1 },
      { text: '    while (l < r) {', indent: 1 },
      { text: '        int area = min(height[l], height[r]) * (r - l);', indent: 2 },
      { text: '        maxA = max(maxA, area);', indent: 2 },
      { text: '        if (height[l] < height[r]) {', indent: 2 },
      { text: '            l++;', indent: 3 },
      { text: '        } else {', indent: 2 },
      { text: '            r--;', indent: 3 },
      { text: '        }', indent: 2 },
      { text: '    }', indent: 1 },
      { text: '    return maxA;', indent: 1 },
      { text: '}', indent: 0 }
    ],
    java: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'public int maxArea(int[] height) {', indent: 0 },
      { text: '    int l = 0, r = height.length - 1;', indent: 1 },
      { text: '    int maxA = 0;', indent: 1 },
      { text: '    while (l < r) {', indent: 1 },
      { text: '        int area = Math.min(height[l], height[r]) * (r - l);', indent: 2 },
      { text: '        maxA = Math.max(maxA, area);', indent: 2 },
      { text: '        if (height[l] < height[r]) {', indent: 2 },
      { text: '            l++;', indent: 3 },
      { text: '        } else {', indent: 2 },
      { text: '            r--;', indent: 3 },
      { text: '        }', indent: 2 },
      { text: '    }', indent: 1 },
      { text: '    return maxA;', indent: 1 },
      { text: '}', indent: 0 }
    ]
  },
  group_anagrams: {
    javascript: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'function groupAnagrams(strs) {', indent: 0 },
      { text: '  let map = new Map();', indent: 1 },
      { text: '  for (let str of strs) {', indent: 1 },
      { text: '    let sorted = str.split("").sort().join("");', indent: 2 },
      { text: '    if (!map.has(sorted)) { map.set(sorted, []); }', indent: 2 },
      { text: '    map.get(sorted).push(str);', indent: 2 },
      { text: '  }', indent: 1 },
      { text: '  return Array.from(map.values());', indent: 1 },
      { text: '}', indent: 0 }
    ],
    python: [
      { text: '# Placeholder spacer', indent: 0 },
      { text: 'def groupAnagrams(strs):', indent: 0 },
      { text: '    ans = {}', indent: 1 },
      { text: '    for s in strs:', indent: 1 },
      { text: '        sorted_s = "".join(sorted(s))', indent: 2 },
      { text: '        if sorted_s not in ans:', indent: 2 },
      { text: '            ans[sorted_s] = []', indent: 3 },
      { text: '        ans[sorted_s].append(s)', indent: 2 },
      { text: '    return list(ans.values())', indent: 1 },
      { text: '# end func', indent: 0 }
    ],
    cpp: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'vector<vector<string>> groupAnagrams(vector<string>& strs) {', indent: 0 },
      { text: '    unordered_map<string, vector<string>> m;', indent: 1 },
      { text: '    for (string s : strs) {', indent: 1 },
      { text: '        string t = s;', indent: 2 },
      { text: '        sort(t.begin(), t.end());', indent: 2 },
      { text: '        m[t].push_back(s);', indent: 2 },
      { text: '    }', indent: 1 },
      { text: '    vector<vector<string>> res;', indent: 1 },
      { text: '    for (auto p : m) {', indent: 1 },
      { text: '        res.push_back(p.second);', indent: 2 },
      { text: '    }', indent: 1 },
      { text: '    return res;', indent: 1 },
      { text: '}', indent: 0 }
    ],
    java: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'public List<List<String>> groupAnagrams(String[] strs) {', indent: 0 },
      { text: '    Map<String, List<String>> map = new HashMap<>();', indent: 1 },
      { text: '    for (String s : strs) {', indent: 1 },
      { text: '        char[] ca = s.toCharArray();', indent: 2 },
      { text: '        Arrays.sort(ca);', indent: 2 },
      { text: '        String key = String.valueOf(ca);', indent: 2 },
      { text: '        if (!map.containsKey(key)) {', indent: 2 },
      { text: '            map.put(key, new ArrayList<>());', indent: 3 },
      { text: '        }', indent: 2 },
      { text: '        map.get(key).add(s);', indent: 2 },
      { text: '    }', indent: 1 },
      { text: '    return new ArrayList<>(map.values());', indent: 1 },
      { text: '}', indent: 0 }
    ]
  },
  threesum: {
    javascript: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'function threeSum(nums) {', indent: 0 },
      { text: '  nums.sort((a, b) => a - b);', indent: 1 },
      { text: '  let res = [];', indent: 1 },
      { text: '  for (let i = 0; i < nums.length - 2; i++) {', indent: 1 },
      { text: '    if (i > 0 && nums[i] === nums[i-1]) continue;', indent: 2 },
      { text: '    let l = i + 1, r = nums.length - 1;', indent: 2 },
      { text: '    while (l < r) {', indent: 2 },
      { text: '      let sum = nums[i] + nums[l] + nums[r];', indent: 3 },
      { text: '      if (sum === 0) {', indent: 3 },
      { text: '        res.push([nums[i], nums[l], nums[r]]);', indent: 4 },
      { text: '        while (l < r && nums[l] === nums[l+1]) l++;', indent: 4 },
      { text: '        while (l < r && nums[r] === nums[r-1]) r--;', indent: 4 },
      { text: '        l++; r--;', indent: 4 },
      { text: '      } else if (sum < 0) { l++; }', indent: 3 },
      { text: '      else { r--; }', indent: 3 },
      { text: '    }', indent: 2 },
      { text: '  }', indent: 1 },
      { text: '  return res;', indent: 1 },
      { text: '}', indent: 0 }
    ],
    python: [
      { text: '# Placeholder spacer', indent: 0 },
      { text: 'def threeSum(nums):', indent: 0 },
      { text: '    nums.sort()', indent: 1 },
      { text: '    res = []', indent: 1 },
      { text: '    for i in range(len(nums) - 2):', indent: 1 },
      { text: '        if i > 0 and nums[i] == nums[i - 1]: continue', indent: 2 },
      { text: '        l, r = i + 1, len(nums) - 1', indent: 2 },
      { text: '        while l < r:', indent: 2 },
      { text: '            s = nums[i] + nums[l] + nums[r]', indent: 3 },
      { text: '            if s == 0:', indent: 3 },
      { text: '                res.append([nums[i], nums[l], nums[r]])', indent: 4 },
      { text: '                while l < r and nums[l] == nums[l + 1]: l += 1', indent: 4 },
      { text: '                while l < r and nums[r] == nums[r - 1]: r -= 1', indent: 4 },
      { text: '                l += 1; r -= 1', indent: 4 },
      { text: '            elif s < 0: l += 1', indent: 3 },
      { text: '            else: r -= 1', indent: 3 },
      { text: '    return res', indent: 1 },
      { text: '# end func', indent: 0 }
    ],
    cpp: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'vector<vector<int>> threeSum(vector<int>& nums) {', indent: 0 },
      { text: '    vector<vector<int>> res;', indent: 1 },
      { text: '    sort(nums.begin(), nums.end());', indent: 1 },
      { text: '    for (int i = 0; i < nums.size() - 2; ++i) {', indent: 1 },
      { text: '        if (i > 0 && nums[i] == nums[i - 1]) continue;', indent: 2 },
      { text: '        int l = i + 1, r = nums.size() - 1;', indent: 2 },
      { text: '        while (l < r) {', indent: 2 },
      { text: '            int s = nums[i] + nums[l] + nums[r];', indent: 3 },
      { text: '            if (s == 0) {', indent: 3 },
      { text: '                res.push_back({nums[i], nums[l], nums[r]});', indent: 4 },
      { text: '                while (l < r && nums[l] == nums[l + 1]) l++;', indent: 4 },
      { text: '                while (l < r && nums[r] == nums[r - 1]) r--;', indent: 4 },
      { text: '                l++; r--;', indent: 4 },
      { text: '            } else if (s < 0) l++;', indent: 3 },
      { text: '            else r--;', indent: 3 },
      { text: '        }', indent: 2 },
      { text: '    }', indent: 1 },
      { text: '    return res;', indent: 1 },
      { text: '}', indent: 0 }
    ],
    java: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'public List<List<Integer>> threeSum(int[] nums) {', indent: 0 },
      { text: '    Arrays.sort(nums);', indent: 1 },
      { text: '    List<List<Integer>> res = new ArrayList<>();', indent: 1 },
      { text: '    for (int i = 0; i < nums.length - 2; i++) {', indent: 1 },
      { text: '        if (i > 0 && nums[i] == nums[i - 1]) continue;', indent: 2 },
      { text: '        int l = i + 1, r = nums.length - 1;', indent: 2 },
      { text: '        while (l < r) {', indent: 2 },
      { text: '            int sum = nums[i] + nums[l] + nums[r];', indent: 3 },
      { text: '            if (sum == 0) {', indent: 3 },
      { text: '                res.add(Arrays.asList(nums[i], nums[l], nums[r]));', indent: 4 },
      { text: '                while (l < r && nums[l] == nums[l+1]) l++;', indent: 4 },
      { text: '                while (l < r && nums[r] == nums[r-1]) r--;', indent: 4 },
      { text: '                l++; r--;', indent: 4 },
      { text: '            } else if (sum < 0) l++;', indent: 3 },
      { text: '            else r--;', indent: 3 },
      { text: '        }', indent: 2 },
      { text: '    }', indent: 1 },
      { text: '    return res;', indent: 1 },
      { text: '}', indent: 0 }
    ]
  },
  longest_substring: {
    javascript: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'function lengthOfLongestSubstring(s) {', indent: 0 },
      { text: '  let set = new Set();', indent: 1 },
      { text: '  let l = 0, maxLen = 0;', indent: 1 },
      { text: '  for (let r = 0; r < s.length; r++) {', indent: 1 },
      { text: '    while (set.has(s[r])) {', indent: 2 },
      { text: '      set.delete(s[l]);', indent: 3 },
      { text: '      l++;', indent: 3 },
      { text: '    }', indent: 2 },
      { text: '    set.add(s[r]);', indent: 2 },
      { text: '    maxLen = Math.max(maxLen, r - l + 1);', indent: 2 },
      { text: '  }', indent: 1 },
      { text: '  return maxLen;', indent: 1 },
      { text: '}', indent: 0 }
    ],
    python: [
      { text: '# Placeholder spacer', indent: 0 },
      { text: 'def lengthOfLongestSubstring(s):', indent: 0 },
      { text: '    char_set = set()', indent: 1 },
      { text: '    l, max_len = 0, 0', indent: 1 },
      { text: '    for r in range(len(s)):', indent: 1 },
      { text: '        while s[r] in char_set:', indent: 2 },
      { text: '            char_set.remove(s[l])', indent: 3 },
      { text: '            l += 1', indent: 3 },
      { text: '        char_set.add(s[r])', indent: 2 },
      { text: '        max_len = max(max_len, r - l + 1)', indent: 2 },
      { text: '    return max_len', indent: 1 },
      { text: '# end func', indent: 0 }
    ],
    cpp: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'int lengthOfLongestSubstring(string s) {', indent: 0 },
      { text: '    unordered_set<char> charSet;', indent: 1 },
      { text: '    int l = 0, maxLen = 0;', indent: 1 },
      { text: '    for (int r = 0; r < s.length(); ++r) {', indent: 1 },
      { text: '        while (charSet.find(s[r]) != charSet.end()) {', indent: 2 },
      { text: '            charSet.erase(s[l]);', indent: 3 },
      { text: '            l++;', indent: 3 },
      { text: '        }', indent: 2 },
      { text: '        charSet.insert(s[r]);', indent: 2 },
      { text: '        maxLen = max(maxLen, r - l + 1);', indent: 2 },
      { text: '    }', indent: 1 },
      { text: '    return maxLen;', indent: 1 },
      { text: '}', indent: 0 }
    ],
    java: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'public int lengthOfLongestSubstring(String s) {', indent: 0 },
      { text: '    Set<Character> set = new HashSet<>();', indent: 1 },
      { text: '    int l = 0, maxLen = 0;', indent: 1 },
      { text: '    for (int r = 0; r < s.length(); r++) {', indent: 1 },
      { text: '        while (set.contains(s.charAt(r))) {', indent: 2 },
      { text: '            set.remove(s.charAt(l));', indent: 3 },
      { text: '            l++;', indent: 3 },
      { text: '        }', indent: 2 },
      { text: '        set.add(s.charAt(r));', indent: 2 },
      { text: '        maxLen = Math.max(maxLen, r - l + 1);', indent: 2 },
      { text: '    }', indent: 1 },
      { text: '    return maxLen;', indent: 1 },
      { text: '}', indent: 0 }
    ]
  },
  merge_two_lists: {
    javascript: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'function mergeTwoLists(list1, list2) {', indent: 0 },
      { text: '  let dummy = new ListNode();', indent: 1 },
      { text: '  let tail = dummy;', indent: 1 },
      { text: '  while (list1 && list2) {', indent: 1 },
      { text: '    if (list1.val < list2.val) {', indent: 2 },
      { text: '      tail.next = list1; list1 = list1.next;', indent: 3 },
      { text: '    } else {', indent: 2 },
      { text: '      tail.next = list2; list2 = list2.next;', indent: 3 },
      { text: '    }', indent: 2 },
      { text: '    tail = tail.next;', indent: 2 },
      { text: '  }', indent: 1 },
      { text: '  tail.next = list1 || list2;', indent: 1 },
      { text: '  return dummy.next;', indent: 1 },
      { text: '}', indent: 0 }
    ],
    python: [
      { text: '# Placeholder spacer', indent: 0 },
      { text: 'def mergeTwoLists(list1, list2):', indent: 0 },
      { text: '    dummy = ListNode()', indent: 1 },
      { text: '    tail = dummy', indent: 1 },
      { text: '    while list1 and list2:', indent: 1 },
      { text: '        if list1.val < list2.val:', indent: 2 },
      { text: '            tail.next = list1', indent: 3 },
      { text: '            list1 = list1.next', indent: 3 },
      { text: '        else:', indent: 2 },
      { text: '            tail.next = list2', indent: 3 },
      { text: '            list2 = list2.next', indent: 3 },
      { text: '        tail = tail.next', indent: 2 },
      { text: '    tail.next = list1 or list2', indent: 1 },
      { text: '    return dummy.next', indent: 1 },
      { text: '# end func', indent: 0 }
    ],
    cpp: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'ListNode* mergeTwoLists(ListNode* list1, ListNode* list2) {', indent: 0 },
      { text: '    ListNode dummy(0);', indent: 1 },
      { text: '    ListNode* tail = &dummy;', indent: 1 },
      { text: '    while (list1 != nullptr && list2 != nullptr) {', indent: 2 },
      { text: '        if (list1->val < list2->val) {', indent: 3 },
      { text: '            tail->next = list1; list1 = list1->next;', indent: 4 },
      { text: '        } else {', indent: 3 },
      { text: '            tail->next = list2; list2 = list2->next;', indent: 4 },
      { text: '        }', indent: 3 },
      { text: '        tail = tail->next;', indent: 3 },
      { text: '    }', indent: 1 },
      { text: '    tail->next = (list1 != nullptr) ? list1 : list2;', indent: 1 },
      { text: '    return dummy.next;', indent: 1 },
      { text: '}', indent: 0 }
    ],
    java: [
      { text: '// Placeholder spacer', indent: 0 },
      { text: 'public ListNode mergeTwoLists(ListNode list1, ListNode list2) {', indent: 0 },
      { text: '    ListNode dummy = new ListNode(0);', indent: 1 },
      { text: '    ListNode tail = dummy;', indent: 1 },
      { text: '    while (list1 != null && list2 != null) {', indent: 2 },
      { text: '        if (list1.val < list2.val) {', indent: 3 },
      { text: '            tail.next = list1; list1 = list1.next;', indent: 4 },
      { text: '        } else {', indent: 3 },
      { text: '            tail.next = list2; list2 = list2.next;', indent: 4 },
      { text: '        }', indent: 3 },
      { text: '        tail = tail->next;', indent: 3 },
      { text: '    }', indent: 1 },
      { text: '    tail.next = (list1 != null) ? list1 : list2;', indent: 1 },
      { text: '    return dummy.next;', indent: 1 },
      { text: '}', indent: 0 }
    ]
  }
};
