import { LeetCodeProblem } from './leetcodeDatabase';

export const NEETCODE_150_PROBLEMS: LeetCodeProblem[] = [
  // ==================== ARRAYS & HASHING (9/9) ====================
  {
    id: 'contains_duplicate',
    number: 217,
    title: 'Contains Duplicate',
    difficulty: 'Easy',
    category: 'Arrays & Hashing',
    neetcodeSection: 'Arrays & Hashing',
    description: 'Given an integer array nums, return true if any value appears at least twice in the array, and false if every element is distinct.',
    inputExample: 'nums = [1,2,3,1]',
    outputExample: 'true',
    acceptance: '61.3%'
  },
  {
    id: 'valid_anagram',
    number: 242,
    title: 'Valid Anagram',
    difficulty: 'Easy',
    category: 'Arrays & Hashing',
    neetcodeSection: 'Arrays & Hashing',
    description: 'Given two strings s and t, return true if t is an anagram of s, and false otherwise.',
    inputExample: 's = "anagram", t = "nagaram"',
    outputExample: 'true',
    acceptance: '64.1%'
  },
  {
    id: 'twosum',
    number: 1,
    title: 'Two Sum',
    difficulty: 'Easy',
    category: 'Arrays & Hashing',
    neetcodeSection: 'Arrays & Hashing',
    description: 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.',
    inputExample: 'nums = [2,7,11,15], target = 9',
    outputExample: '[0, 1]',
    acceptance: '51.3%'
  },
  {
    id: 'group_anagrams',
    number: 49,
    title: 'Group Anagrams',
    difficulty: 'Medium',
    category: 'Arrays & Hashing',
    neetcodeSection: 'Arrays & Hashing',
    description: 'Given an array of strings strs, group the anagrams together. You can return the answer in any order.',
    inputExample: 'strs = ["eat","tea","tan","ate","nat","bat"]',
    outputExample: '[["bat"],["nat","tan"],["ate","eat","tea"]]',
    acceptance: '68.1%'
  },
  {
    id: 'top_k_frequent',
    number: 347,
    title: 'Top K Frequent Elements',
    difficulty: 'Medium',
    category: 'Arrays & Hashing',
    neetcodeSection: 'Arrays & Hashing',
    description: 'Given an integer array nums and an integer k, return the k most frequent elements. You may return the answer in any order.',
    inputExample: 'nums = [1,1,1,2,2,3], k = 2',
    outputExample: '[1, 2]',
    acceptance: '63.2%'
  },
  {
    id: 'product_except_self',
    number: 238,
    title: 'Product of Array Except Self',
    difficulty: 'Medium',
    category: 'Arrays & Hashing',
    neetcodeSection: 'Arrays & Hashing',
    description: 'Given an integer array nums, return an array answer such that answer[i] is equal to the product of all the elements of nums except nums[i] in O(n) without using division.',
    inputExample: 'nums = [1,2,3,4]',
    outputExample: '[24,12,8,6]',
    acceptance: '65.4%'
  },
  {
    id: 'valid_sudoku',
    number: 36,
    title: 'Valid Sudoku',
    difficulty: 'Medium',
    category: 'Arrays & Hashing',
    neetcodeSection: 'Arrays & Hashing',
    description: 'Determine if a 9 x 9 Sudoku board is valid. Only the filled cells must be validated according to the Sudoku validation rules.',
    inputExample: 'board = [["5","3",".",".","7",".",".",".","."],...]',
    outputExample: 'true',
    acceptance: '58.7%'
  },
  {
    id: 'encode_decode_strings',
    number: 659,
    title: 'Encode and Decode Strings',
    difficulty: 'Medium',
    category: 'Arrays & Hashing',
    neetcodeSection: 'Arrays & Hashing',
    description: 'Design an algorithm to encode a list of strings to a single string, which is then decoded back to the original list of strings.',
    inputExample: 'dummy_input = ["lint","code","love","you"]',
    outputExample: '["lint","code","love","you"]',
    acceptance: '62.0%'
  },
  {
    id: 'longest_consecutive',
    number: 128,
    title: 'Longest Consecutive Sequence',
    difficulty: 'Medium',
    category: 'Arrays & Hashing',
    neetcodeSection: 'Arrays & Hashing',
    description: 'Given an unsorted array of integers nums, return the length of the longest consecutive elements sequence in O(n) time.',
    inputExample: 'nums = [100,4,200,1,3,2]',
    outputExample: '4',
    acceptance: '48.9%'
  },

  // ==================== TWO POINTERS (5/5) ====================
  {
    id: 'valid_palindrome',
    number: 125,
    title: 'Valid Palindrome',
    difficulty: 'Easy',
    category: 'Two Pointers',
    neetcodeSection: 'Two Pointers',
    description: 'A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward.',
    inputExample: 's = "A man, a plan, a canal: Panama"',
    outputExample: 'true',
    acceptance: '46.2%'
  },
  {
    id: 'twosum_ii',
    number: 167,
    title: 'Two Sum II - Input Array Is Sorted',
    difficulty: 'Medium',
    category: 'Two Pointers',
    neetcodeSection: 'Two Pointers',
    description: 'Given a 1-indexed array of integers numbers that is already sorted in non-decreasing order, find two numbers such that they add up to a specific target number.',
    inputExample: 'numbers = [2,7,11,15], target = 9',
    outputExample: '[1, 2]',
    acceptance: '60.5%'
  },
  {
    id: 'threesum',
    number: 15,
    title: '3Sum',
    difficulty: 'Medium',
    category: 'Two Pointers',
    neetcodeSection: 'Two Pointers',
    description: 'Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.',
    inputExample: 'nums = [-1,0,1,2,-1,-4]',
    outputExample: '[[-1,-1,2],[-1,0,1]]',
    acceptance: '34.7%'
  },
  {
    id: 'container_with_most_water',
    number: 11,
    title: 'Container With Most Water',
    difficulty: 'Medium',
    category: 'Two Pointers',
    neetcodeSection: 'Two Pointers',
    description: 'You are given an integer array height of length n. Find two lines that together with the x-axis form a container, such that the container contains the most water.',
    inputExample: 'height = [1,8,6,2,5,4,8,3,7]',
    outputExample: '49',
    acceptance: '54.2%'
  },
  {
    id: 'trapping_rain_water',
    number: 42,
    title: 'Trapping Rain Water',
    difficulty: 'Hard',
    category: 'Two Pointers',
    neetcodeSection: 'Two Pointers',
    description: 'Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.',
    inputExample: 'height = [0,1,0,2,1,0,1,3,2,1,2,1]',
    outputExample: '6',
    acceptance: '61.4%'
  },

  // ==================== SLIDING WINDOW (6/6) ====================
  {
    id: 'buy_sell_stock',
    number: 121,
    title: 'Best Time to Buy and Sell Stock',
    difficulty: 'Easy',
    category: 'Sliding Window',
    neetcodeSection: 'Sliding Window',
    description: 'You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.',
    inputExample: 'prices = [7,1,5,3,6,4]',
    outputExample: '5',
    acceptance: '53.6%'
  },
  {
    id: 'longest_substring',
    number: 3,
    title: 'Longest Substring Without Repeating Characters',
    difficulty: 'Medium',
    category: 'Sliding Window',
    neetcodeSection: 'Sliding Window',
    description: 'Given a string s, find the length of the longest substring without repeating characters.',
    inputExample: 's = "abcabcbb"',
    outputExample: '3',
    acceptance: '34.6%'
  },
  {
    id: 'longest_repeating_replacement',
    number: 424,
    title: 'Longest Repeating Character Replacement',
    difficulty: 'Medium',
    category: 'Sliding Window',
    neetcodeSection: 'Sliding Window',
    description: 'You are given a string s and an integer k. You can choose any character of the string and change it to any other uppercase English character. Perform this operation at most k times to find the longest substring containing same letters.',
    inputExample: 's = "ABAB", k = 2',
    outputExample: '4',
    acceptance: '54.8%'
  },
  {
    id: 'permutation_in_string',
    number: 567,
    title: 'Permutation in String',
    difficulty: 'Medium',
    category: 'Sliding Window',
    neetcodeSection: 'Sliding Window',
    description: 'Given two strings s1 and s2, return true if s2 contains a permutation of s1, or false otherwise.',
    inputExample: 's1 = "ab", s2 = "eidbaooo"',
    outputExample: 'true',
    acceptance: '44.5%'
  },
  {
    id: 'minimum_window_substring',
    number: 76,
    title: 'Minimum Window Substring',
    difficulty: 'Hard',
    category: 'Sliding Window',
    neetcodeSection: 'Sliding Window',
    description: 'Given two strings s and t of lengths m and n respectively, return the minimum window substring of s such that every character in t (including duplicates) is included in the window.',
    inputExample: 's = "ADOBECODEBANC", t = "ABC"',
    outputExample: '"BANC"',
    acceptance: '41.9%'
  },
  {
    id: 'sliding_window_maximum',
    number: 239,
    title: 'Sliding Window Maximum',
    difficulty: 'Hard',
    category: 'Sliding Window',
    neetcodeSection: 'Sliding Window',
    description: 'You are given an array of integers nums, there is a sliding window of size k which is moving from the very left of the array to the very right. Return the max sliding window values.',
    inputExample: 'nums = [1,3,-1,-3,5,3,6,7], k = 3',
    outputExample: '[3,3,5,5,6,7]',
    acceptance: '46.7%'
  },

  // ==================== STACK (7/7) ====================
  {
    id: 'valid_parentheses',
    number: 20,
    title: 'Valid Parentheses',
    difficulty: 'Easy',
    category: 'Stack',
    neetcodeSection: 'Stack',
    description: 'Given a string s containing just the characters brackets, determine if the input string is valid.',
    inputExample: 's = "()[]{}"',
    outputExample: 'true',
    acceptance: '40.8%'
  },
  {
    id: 'min_stack',
    number: 155,
    title: 'Min Stack',
    difficulty: 'Medium',
    category: 'Stack',
    neetcodeSection: 'Stack',
    description: 'Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.',
    inputExample: '["MinStack","push","push","push","getMin","pop","top","getMin"]',
    outputExample: '[null,null,null,null,-3,null,0,-2]',
    acceptance: '53.1%'
  },
  {
    id: 'evaluate_reverse_polish',
    number: 150,
    title: 'Evaluate Reverse Polish Notation',
    difficulty: 'Medium',
    category: 'Stack',
    neetcodeSection: 'Stack',
    description: 'You are given an array of strings tokens representing an arithmetic expression in a Reverse Polish Notation. Evaluate the expression and return its value.',
    inputExample: 'tokens = ["2","1","+","3","*"]',
    outputExample: '9',
    acceptance: '49.2%'
  },
  {
    id: 'generate_parentheses',
    number: 22,
    title: 'Generate Parentheses',
    difficulty: 'Medium',
    category: 'Stack',
    neetcodeSection: 'Stack',
    description: 'Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.',
    inputExample: 'n = 3',
    outputExample: '["((()))","(()())","(())()","()(())","()()()"]',
    acceptance: '73.4%'
  },
  {
    id: 'daily_temperatures',
    number: 739,
    title: 'Daily Temperatures',
    difficulty: 'Medium',
    category: 'Stack',
    neetcodeSection: 'Stack',
    description: 'Given an array of integers temperatures represents the daily temperatures, return an array answer such that answer[i] is the number of days you have to wait after the i-th day to get a warmer temperature.',
    inputExample: 'temperatures = [73,74,75,71,69,72,76,73]',
    outputExample: '[1,1,4,2,1,1,0,0]',
    acceptance: '66.0%'
  },
  {
    id: 'car_fleet',
    number: 853,
    title: 'Car Fleet',
    difficulty: 'Medium',
    category: 'Stack',
    neetcodeSection: 'Stack',
    description: 'There are n cars at given positions moving towards a destination. Cars cannot pass each other. Calculate how many car fleets will arrive at the destination.',
    inputExample: 'target = 12, position = [10,8,0,5,3], speed = [2,4,1,1,3]',
    outputExample: '3',
    acceptance: '50.1%'
  },
  {
    id: 'largest_rectangle_histogram',
    number: 84,
    title: 'Largest Rectangle in Histogram',
    difficulty: 'Hard',
    category: 'Stack',
    neetcodeSection: 'Stack',
    description: 'Given an array of integers heights representing the histogram\'s bar height where the width of each bar is 1, find the area of the largest rectangle in the histogram.',
    inputExample: 'heights = [2,1,5,6,2,3]',
    outputExample: '10',
    acceptance: '44.3%'
  },

  // ==================== BINARY SEARCH (7/7) ====================
  {
    id: 'binary_search',
    number: 704,
    title: 'Binary Search',
    difficulty: 'Easy',
    category: 'Binary Search',
    neetcodeSection: 'Binary Search',
    description: 'Given an array of integers nums which is sorted in ascending order, and an integer target, write a function to search target in nums in O(log n) time.',
    inputExample: 'nums = [-1,0,3,5,9,12], target = 9',
    outputExample: '4',
    acceptance: '56.9%'
  },
  {
    id: 'search_2d_matrix',
    number: 74,
    title: 'Search a 2D Matrix',
    difficulty: 'Medium',
    category: 'Binary Search',
    neetcodeSection: 'Binary Search',
    description: 'You are given an m x n integer matrix matrix with properties: sorted rows, and first element of row > last element of previous; find target.',
    inputExample: 'matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 3',
    outputExample: 'true',
    acceptance: '49.8%'
  },
  {
    id: 'koko_eating_bananas',
    number: 875,
    title: 'Koko Eating Bananas',
    difficulty: 'Medium',
    category: 'Binary Search',
    neetcodeSection: 'Binary Search',
    description: 'Koko loves to eat bananas. There are n piles of bananas, and H hours. Find the minimum integer speed K to eat all bananas within H hours.',
    inputExample: 'piles = [3,6,7,11], h = 8',
    outputExample: '4',
    acceptance: '52.7%'
  },
  {
    id: 'find_min_rotated_sorted',
    number: 153,
    title: 'Find Minimum in Rotated Sorted Array',
    difficulty: 'Medium',
    category: 'Binary Search',
    neetcodeSection: 'Binary Search',
    description: 'Suppose an array of length n sorted in ascending order is rotated between 1 and n times. Find the minimum element of this array in O(log n) time.',
    inputExample: 'nums = [3,4,5,1,2]',
    outputExample: '1',
    acceptance: '49.5%'
  },
  {
    id: 'search_rotated_sorted',
    number: 33,
    title: 'Search in Rotated Sorted Array',
    difficulty: 'Medium',
    category: 'Binary Search',
    neetcodeSection: 'Binary Search',
    description: 'Given the array nums after the possible rotation and an integer target, return the index of target if it is in nums, or -1 otherwise.',
    inputExample: 'nums = [4,5,6,7,0,1,2], target = 0',
    outputExample: '4',
    acceptance: '40.2%'
  },
  {
    id: 'time_key_value_store',
    number: 981,
    title: 'Time Based Key-Value Store',
    difficulty: 'Medium',
    category: 'Binary Search',
    neetcodeSection: 'Binary Search',
    description: 'Design a time-based key-value data structure that can store multiple values for the same key at different time stamps and retrieve the key\'s value at a certain timestamp.',
    inputExample: '["TimeMap","set","get","get","set","get","get"]',
    outputExample: '[null,null,"bar","bar",null,"bar2","bar2"]',
    acceptance: '53.1%'
  },
  {
    id: 'median_two_sorted_arrays',
    number: 4,
    title: 'Median of Two Sorted Arrays',
    difficulty: 'Hard',
    category: 'Binary Search',
    neetcodeSection: 'Binary Search',
    description: 'Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays in O(log (m+n)) runtime.',
    inputExample: 'nums1 = [1,3], nums2 = [2]',
    outputExample: '2.0',
    acceptance: '38.6%'
  },

  // ==================== LINKED LIST (11/11) ====================
  {
    id: 'reverse_list',
    number: 206,
    title: 'Reverse Linked List',
    difficulty: 'Easy',
    category: 'Linked List',
    neetcodeSection: 'Linked List',
    description: 'Given the head of a singly linked list, reverse the list, and return the reversed list.',
    inputExample: 'head = [1,2,3,4,5]',
    outputExample: '[5,4,3,2,1]',
    acceptance: '75.2%'
  },
  {
    id: 'merge_two_lists',
    number: 21,
    title: 'Merge Two Sorted Lists',
    difficulty: 'Easy',
    category: 'Linked List',
    neetcodeSection: 'Linked List',
    description: 'You are given the heads of two sorted linked lists list1 and list2. Merge the two lists into one sorted list and return its head.',
    inputExample: 'list1 = [1,2,4], list2 = [1,3,4]',
    outputExample: '[1,1,2,3,4,4]',
    acceptance: '64.3%'
  },
  {
    id: 'reorder_list',
    number: 143,
    title: 'Reorder List',
    difficulty: 'Medium',
    category: 'Linked List',
    neetcodeSection: 'Linked List',
    description: 'You are given the head of a singly linked-list. Reorder the list to be: L0 -> Ln -> L1 -> Ln-1 -> L2 -> Ln-2...',
    inputExample: 'head = [1,2,3,4]',
    outputExample: '[1,4,2,3]',
    acceptance: '54.5%'
  },
  {
    id: 'remove_nth_node_end',
    number: 19,
    title: 'Remove Nth Node From End of List',
    difficulty: 'Medium',
    category: 'Linked List',
    neetcodeSection: 'Linked List',
    description: 'Given the head of a linked list, remove the nth node from the end of the list and return its head.',
    inputExample: 'head = [1,2,3,4,5], n = 2',
    outputExample: '[1,2,3,5]',
    acceptance: '44.3%'
  },
  {
    id: 'copy_list_random_pointer',
    number: 138,
    title: 'Copy List with Random Pointer',
    difficulty: 'Medium',
    category: 'Linked List',
    neetcodeSection: 'Linked List',
    description: 'Construct a deep copy of a linked list where each node contains an additional random pointer, pointing to any node in the list, or null.',
    inputExample: 'head = [[7,null],[13,0],[11,4],[10,2],[1,0]]',
    outputExample: '[[7,null],[13,0],[11,4],[10,2],[1,0]]',
    acceptance: '54.1%'
  },
  {
    id: 'add_two_numbers_list',
    number: 2,
    title: 'Add Two Numbers',
    difficulty: 'Medium',
    category: 'Linked List',
    neetcodeSection: 'Linked List',
    description: 'You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.',
    inputExample: 'l1 = [2,4,3], l2 = [5,6,4]',
    outputExample: '[7,0,8]',
    acceptance: '41.3%'
  },
  {
    id: 'linked_list_cycle',
    number: 141,
    title: 'Linked List Cycle',
    difficulty: 'Easy',
    category: 'Linked List',
    neetcodeSection: 'Linked List',
    description: 'Given head, the head of a linked list, determine if the linked list has a cycle in it. Do so using O(1) memory.',
    inputExample: 'head = [3,2,0,-4], pos = 1',
    outputExample: 'true',
    acceptance: '48.4%'
  },
  {
    id: 'find_duplicate_number',
    number: 287,
    title: 'Find the Duplicate Number',
    difficulty: 'Medium',
    category: 'Linked List',
    neetcodeSection: 'Linked List',
    description: 'Given an array of integers nums containing n + 1 integers where each integer is in the range [1, n] inclusive. There is only one repeated number in nums, find this repeated number in O(1) space.',
    inputExample: 'nums = [1,3,4,2,2]',
    outputExample: '2',
    acceptance: '59.2%'
  },
  {
    id: 'lru_cache',
    number: 146,
    title: 'LRU Cache',
    difficulty: 'Medium',
    category: 'Linked List',
    neetcodeSection: 'Linked List',
    description: 'Design a data structure that follows the constraints of a Least Recently Used (LRU) cache, supporting O(1) get and put operations.',
    inputExample: '["LRUCache","put","put","get","put","get","put","get","get","get"]',
    outputExample: '[null,null,null,1,null,-1,null,-1,3,4]',
    acceptance: '41.5%'
  },
  {
    id: 'merge_k_sorted_lists',
    number: 23,
    title: 'Merge k Sorted Lists',
    difficulty: 'Hard',
    category: 'Linked List',
    neetcodeSection: 'Linked List',
    description: 'You are given an array of k linked-lists lists, each linked-list is sorted in ascending order. Merge all the linked-lists into one sorted linked-list and return it.',
    inputExample: 'lists = [[1,4,5],[1,3,4],[2,6]]',
    outputExample: '[1,1,2,3,4,4,5,6]',
    acceptance: '51.8%'
  },
  {
    id: 'reverse_nodes_k_group',
    number: 25,
    title: 'Reverse Nodes in k-Group',
    difficulty: 'Hard',
    category: 'Linked List',
    neetcodeSection: 'Linked List',
    description: 'Given the head of a linked list, reverse the nodes of the list k at a time, and return the modified list.',
    inputExample: 'head = [1,2,3,4,5], k = 2',
    outputExample: '[2,1,4,3,5]',
    acceptance: '57.4%'
  },

  // ==================== TREES (15/15) ====================
  {
    id: 'invert_tree',
    number: 226,
    title: 'Invert Binary Tree',
    difficulty: 'Easy',
    category: 'Trees',
    neetcodeSection: 'Trees',
    description: 'Given the root of a binary tree, invert the tree, and return its root.',
    inputExample: 'root = [4,2,7,1,3,6,9]',
    outputExample: '[4,7,2,9,6,3,1]',
    acceptance: '76.8%'
  },
  {
    id: 'max_depth_binary_tree',
    number: 104,
    title: 'Maximum Depth of Binary Tree',
    difficulty: 'Easy',
    category: 'Trees',
    neetcodeSection: 'Trees',
    description: 'Given the root of a binary tree, return its maximum depth (number of nodes along the longest path from the root node down to the farthest leaf node).',
    inputExample: 'root = [3,9,20,null,null,15,7]',
    outputExample: '3',
    acceptance: '74.6%'
  },
  {
    id: 'diameter_binary_tree',
    number: 543,
    title: 'Diameter of Binary Tree',
    difficulty: 'Easy',
    category: 'Trees',
    neetcodeSection: 'Trees',
    description: 'Given the root of a binary tree, return the length of the diameter of the tree. The diameter of a binary tree is the length of the longest path between any two nodes in a tree.',
    inputExample: 'root = [1,2,3,4,5]',
    outputExample: '3',
    acceptance: '58.3%'
  },
  {
    id: 'balanced_binary_tree',
    number: 110,
    title: 'Balanced Binary Tree',
    difficulty: 'Easy',
    category: 'Trees',
    neetcodeSection: 'Trees',
    description: 'Given a binary tree, determine if it is height-balanced (depth of the two subtrees of every node never differs by more than 1).',
    inputExample: 'root = [3,9,20,null,null,15,7]',
    outputExample: 'true',
    acceptance: '50.9%'
  },
  {
    id: 'same_tree',
    number: 100,
    title: 'Same Tree',
    difficulty: 'Easy',
    category: 'Trees',
    neetcodeSection: 'Trees',
    description: 'Given the roots of two binary trees p and q, write a function to check if they are the same or not.',
    inputExample: 'p = [1,2,3], q = [1,2,3]',
    outputExample: 'true',
    acceptance: '59.8%'
  },
  {
    id: 'subtree_tree',
    number: 572,
    title: 'Subtree of Another Tree',
    difficulty: 'Easy',
    category: 'Trees',
    neetcodeSection: 'Trees',
    description: 'Given the roots of two binary trees root and subRoot, return true if there is a subtree of root with the same structure and node values of subRoot.',
    inputExample: 'root = [3,4,5,1,2], subRoot = [4,1,2]',
    outputExample: 'true',
    acceptance: '47.5%'
  },
  {
    id: 'lca_bst',
    number: 235,
    title: 'Lowest Common Ancestor of a Binary Search Tree',
    difficulty: 'Easy',
    category: 'Trees',
    neetcodeSection: 'Trees',
    description: 'Given a binary search tree (BST), find the lowest common ancestor (LCA) node of two given nodes in the BST.',
    inputExample: 'root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 8',
    outputExample: '6',
    acceptance: '63.0%'
  },
  {
    id: 'level_order_traversal',
    number: 102,
    title: 'Binary Tree Level Order Traversal',
    difficulty: 'Medium',
    category: 'Trees',
    neetcodeSection: 'Trees',
    description: 'Given the root of a binary tree, return the level order traversal of its nodes\' values. (i.e., from left to right, level by level).',
    inputExample: 'root = [3,9,20,null,null,15,7]',
    outputExample: '[[3],[9,20],[15,7]]',
    acceptance: '66.2%'
  },
  {
    id: 'right_side_view',
    number: 199,
    title: 'Binary Tree Right Side View',
    difficulty: 'Medium',
    category: 'Trees',
    neetcodeSection: 'Trees',
    description: 'Given the root of a binary tree, imagine yourself standing on the right side of it, return the values of the nodes you can see ordered from top to bottom.',
    inputExample: 'root = [1,2,3,null,5,null,4]',
    outputExample: '[1,3,4]',
    acceptance: '62.5%'
  },
  {
    id: 'count_good_nodes',
    number: 1448,
    title: 'Count Good Nodes in Binary Tree',
    difficulty: 'Medium',
    category: 'Trees',
    neetcodeSection: 'Trees',
    description: 'Given a binary tree root, a node x in the tree is named good if in the path from root to x there are no nodes with a value greater than x. Return the number of good nodes.',
    inputExample: 'root = [3,1,4,3,null,1,5]',
    outputExample: '4',
    acceptance: '73.2%'
  },
  {
    id: 'validate_bst',
    number: 98,
    title: 'Validate Binary Search Tree',
    difficulty: 'Medium',
    category: 'Trees',
    neetcodeSection: 'Trees',
    description: 'Given the root of a binary tree, determine if it is a valid binary search tree (BST). Left subtree has keys < node\'s key; right subtree has keys > node\'s key.',
    inputExample: 'root = [2,1,3]',
    outputExample: 'true',
    acceptance: '32.6%'
  },
  {
    id: 'kth_smallest_bst',
    number: 230,
    title: 'Kth Smallest Element in a BST',
    difficulty: 'Medium',
    category: 'Trees',
    neetcodeSection: 'Trees',
    description: 'Given the root of a binary search tree, and an integer k, return the kth smallest value (1-indexed) of all the values of the nodes in the tree.',
    inputExample: 'root = [3,1,4,null,2], k = 1',
    outputExample: '1',
    acceptance: '71.5%'
  },
  {
    id: 'construct_binary_tree_pre_in',
    number: 105,
    title: 'Construct Binary Tree from Preorder and Inorder Traversal',
    difficulty: 'Medium',
    category: 'Trees',
    neetcodeSection: 'Trees',
    description: 'Given two integer arrays preorder and inorder where preorder is the preorder traversal of a binary tree and inorder is the inorder traversal of the same tree, construct and return the binary tree.',
    inputExample: 'preorder = [3,9,20,15,7], inorder = [9,3,15,20,7]',
    outputExample: '[3,9,20,null,null,15,7]',
    acceptance: '62.8%'
  },
  {
    id: 'binary_tree_max_path_sum',
    number: 124,
    title: 'Binary Tree Maximum Path Sum',
    difficulty: 'Hard',
    category: 'Trees',
    neetcodeSection: 'Trees',
    description: 'A path in a binary tree is a sequence of nodes where each pair of adjacent nodes in the sequence has an edge connecting them. Find the maximum path sum of any non-empty path.',
    inputExample: 'root = [-10,9,20,null,null,15,7]',
    outputExample: '42',
    acceptance: '39.6%'
  },
  {
    id: 'serialize_deserialize_tree',
    number: 297,
    title: 'Serialize and Deserialize Binary Tree',
    difficulty: 'Hard',
    category: 'Trees',
    neetcodeSection: 'Trees',
    description: 'Design an algorithm to serialize a binary tree to a string and deserialize this string back to the binary tree structure.',
    inputExample: 'root = [1,2,3,null,null,4,5]',
    outputExample: '[1,2,3,null,null,4,5]',
    acceptance: '56.4%'
  },

  // ==================== TRIES (3/3) ====================
  {
    id: 'implement_trie',
    number: 208,
    title: 'Implement Trie (Prefix Tree)',
    difficulty: 'Medium',
    category: 'Tries',
    neetcodeSection: 'Tries',
    description: 'A trie (pronounced as "try") or prefix tree is a tree data structure used to efficiently store and retrieve keys in a dataset of strings. Implement trie with insert, search, and startsWith methods.',
    inputExample: '["Trie","insert","search","search","startsWith","insert","search"]',
    outputExample: '[null,null,true,false,true,null,true]',
    acceptance: '64.0%'
  },
  {
    id: 'design_add_search_words',
    number: 211,
    title: 'Design Add and Search Words Data Structure',
    difficulty: 'Medium',
    category: 'Tries',
    neetcodeSection: 'Tries',
    description: 'Design a data structure that supports adding new words and finding if a word exists in the structure, supporting dot wildcard ".", matching any letter.',
    inputExample: '["WordDictionary","addWord","addWord","search","search"]',
    outputExample: '[null,null,null,true,true]',
    acceptance: '44.8%'
  },
  {
    id: 'word_search_ii',
    number: 212,
    title: 'Word Search II',
    difficulty: 'Hard',
    category: 'Tries',
    neetcodeSection: 'Tries',
    description: 'Given an m x n board of characters and a list of strings words, return all words on the board. Each word must be constructed from letters of sequentially adjacent cells.',
    inputExample: 'board = [["o","a","a","n"],["e","t","a","e"]], words = ["oath","pea"]',
    outputExample: '["oath"]',
    acceptance: '38.2%'
  },

  // ==================== HEEP / PRIORITY QUEUE (7/7) ====================
  {
    id: 'kth_largest_stream',
    number: 703,
    title: 'Kth Largest Element in a Stream',
    difficulty: 'Easy',
    category: 'Heap / Priority Queue',
    neetcodeSection: 'Heap / Priority Queue',
    description: 'Design a class to find the kth largest element in a stream. Note that it is the kth largest element in the sorted order, not the kth distinct element.',
    inputExample: '["KthLargest","add","add","add"]',
    outputExample: '[null,4,5,5]',
    acceptance: '56.9%'
  },
  {
    id: 'last_stone_weight',
    number: 1046,
    title: 'Last Stone Weight',
    difficulty: 'Easy',
    category: 'Heap / Priority Queue',
    neetcodeSection: 'Heap / Priority Queue',
    description: 'You are given an array of integers stones where stones[i] is the weight of the i-th stone. We play a game smashing the heaviest stones until at most 1 stone remains.',
    inputExample: 'stones = [2,7,4,1,8,1]',
    outputExample: '1',
    acceptance: '65.3%'
  },
  {
    id: 'k_closest_points',
    number: 973,
    title: 'K Closest Points to Origin',
    difficulty: 'Medium',
    category: 'Heap / Priority Queue',
    neetcodeSection: 'Heap / Priority Queue',
    description: 'Given an array of points where points[i] = [xi, yi] and an integer k, return the k closest points to the origin (0, 0) calculated via Euclidean distance.',
    inputExample: 'points = [[1,3],[-2,2]], k = 1',
    outputExample: '[[-2,2]]',
    acceptance: '66.1%'
  },
  {
    id: 'kth_largest_array',
    number: 215,
    title: 'Kth Largest Element in an Array',
    difficulty: 'Medium',
    category: 'Heap / Priority Queue',
    neetcodeSection: 'Heap / Priority Queue',
    description: 'Given an integer array nums and an integer k, return the kth largest element in the array.',
    inputExample: 'nums = [3,2,1,5,6,4], k = 2',
    outputExample: '5',
    acceptance: '66.8%'
  },
  {
    id: 'task_scheduler',
    number: 621,
    title: 'Task Scheduler',
    difficulty: 'Medium',
    category: 'Heap / Priority Queue',
    neetcodeSection: 'Heap / Priority Queue',
    description: 'Given a characters array tasks, representing the tasks a CPU needs to do, and a cooling cooldown gap n. Find the minimum CPU cycles to complete all tasks.',
    inputExample: 'tasks = ["A","A","A","B","B","B"], n = 2',
    outputExample: '8',
    acceptance: '57.3%'
  },
  {
    id: 'design_twitter',
    number: 355,
    title: 'Design Twitter',
    difficulty: 'Medium',
    category: 'Heap / Priority Queue',
    neetcodeSection: 'Heap / Priority Queue',
    description: 'Design a simplified version of Twitter where users can post tweets, follow/unfollow and see the 10 most recent tweets in feed.',
    inputExample: '["Twitter","postTweet","getNewsFeed","follow","postTweet","getNewsFeed"]',
    outputExample: '[null,null,[5],null,null,[6,5]]',
    acceptance: '38.5%'
  },
  {
    id: 'find_median_data_stream',
    number: 295,
    title: 'Find Median from Data Stream',
    difficulty: 'Hard',
    category: 'Heap / Priority Queue',
    neetcodeSection: 'Heap / Priority Queue',
    description: 'The median is the middle value in an ordered integer list. Implement the MedianFinder class to support adding numbers and calculating current median in O(log n) time.',
    inputExample: '["MedianFinder","addNum","addNum","findMedian","addNum","findMedian"]',
    outputExample: '[null,null,null,1.5,null,2.0]',
    acceptance: '51.9%'
  },

  // ==================== BACKTRACKING (9/9) ====================
  {
    id: 'subsets',
    number: 78,
    title: 'Subsets',
    difficulty: 'Medium',
    category: 'Backtracking',
    neetcodeSection: 'Backtracking',
    description: 'Given an integer array nums of unique elements, return all possible subsets (the power set).',
    inputExample: 'nums = [1,2,3]',
    outputExample: '[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]',
    acceptance: '76.4%'
  },
  {
    id: 'combination_sum',
    number: 39,
    title: 'Combination Sum',
    difficulty: 'Medium',
    category: 'Backtracking',
    neetcodeSection: 'Backtracking',
    description: 'Given an array of distinct integers candidates and a target integer target, return any order list of all unique combinations where chosen candidates sum up to target.',
    inputExample: 'candidates = [2,3,6,7], target = 7',
    outputExample: '[[2,2,3],[7]]',
    acceptance: '70.2%'
  },
  {
    id: 'permutations',
    number: 46,
    title: 'Permutations',
    difficulty: 'Medium',
    category: 'Backtracking',
    neetcodeSection: 'Backtracking',
    description: 'Given an array nums of distinct integers, return all the possible permutations. You can return the answer in any order.',
    inputExample: 'nums = [1,2,3]',
    outputExample: '[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]',
    acceptance: '77.8%'
  },
  {
    id: 'subsets_ii',
    number: 90,
    title: 'Subsets II',
    difficulty: 'Medium',
    category: 'Backtracking',
    neetcodeSection: 'Backtracking',
    description: 'Given an integer array nums that may contain duplicates, return all possible subsets. Solution must not contain duplicate subsets.',
    inputExample: 'nums = [1,2,2]',
    outputExample: '[[],[1],[1,2],[1,2,2],[2],[2,2]]',
    acceptance: '56.9%'
  },
  {
    id: 'combination_sum_ii',
    number: 40,
    title: 'Combination Sum II',
    difficulty: 'Medium',
    category: 'Backtracking',
    neetcodeSection: 'Backtracking',
    description: 'Given a collection of candidate numbers (candidates) and a target number (target), find all unique combinations in candidates where the candidate numbers sum to target. Each number in candidates may only be used once.',
    inputExample: 'candidates = [10,1,2,7,6,1,5], target = 8',
    outputExample: '[[1,1,6],[1,2,5],[1,7],[2,6]]',
    acceptance: '54.1%'
  },
  {
    id: 'word_search',
    number: 79,
    title: 'Word Search',
    difficulty: 'Medium',
    category: 'Backtracking',
    neetcodeSection: 'Backtracking',
    description: 'Given an m x n grid of characters board and a string word, return true if word exists in the grid.',
    inputExample: 'board = [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], word = "ABCCED"',
    outputExample: 'true',
    acceptance: '41.1%'
  },
  {
    id: 'palindrome_partitioning',
    number: 131,
    title: 'Palindrome Partitioning',
    difficulty: 'Medium',
    category: 'Backtracking',
    neetcodeSection: 'Backtracking',
    description: 'Given a string s, partition s such that every substring of the partition is a palindrome. Return all possible palindrome partitioning of s.',
    inputExample: 's = "aab"',
    outputExample: '[["a","a","b"],["aa","b"]]',
    acceptance: '65.8%'
  },
  {
    id: 'n_queens',
    number: 51,
    title: 'N-Queens',
    difficulty: 'Hard',
    category: 'Backtracking',
    neetcodeSection: 'Backtracking',
    description: 'The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other. Return all distinct solutions.',
    inputExample: 'n = 4',
    outputExample: '[[".Q..","...Q","Q...","..Q."],["..Q.","Q...","...Q",".Q.."]]',
    acceptance: '66.8%'
  },
  {
    id: 'letter_combinations_phone',
    number: 17,
    title: 'Letter Combinations of a Phone Number',
    difficulty: 'Medium',
    category: 'Backtracking',
    neetcodeSection: 'Backtracking',
    description: 'Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. Map digits to letters like a telephone keypad.',
    inputExample: 'digits = "23"',
    outputExample: '["ad","ae","af","bd","be","bf","cd","ce","cf"]',
    acceptance: '59.1%'
  },

  // ==================== GRAPHS (13/13) ====================
  {
    id: 'number_of_islands',
    number: 200,
    title: 'Number of Islands',
    difficulty: 'Medium',
    category: 'Graphs',
    neetcodeSection: 'Graphs',
    description: 'Given an m x n 2D binary grid grid which represents a map of "1"s (land) and "0"s (water), return the number of islands.',
    inputExample: 'grid = [["1","1","0","0","0"],["1","1","0","0","0"],["0","0","0","0","0"]]',
    outputExample: '1',
    acceptance: '58.3%'
  },
  {
    id: 'clone_graph',
    number: 133,
    title: 'Clone Graph',
    difficulty: 'Medium',
    category: 'Graphs',
    neetcodeSection: 'Graphs',
    description: 'Given a reference of a node in a connected undirected graph. Return a deep clone (copy) of the graph.',
    inputExample: 'adjList = [[2,4],[1,3],[2,4],[1,3]]',
    outputExample: '[[2,4],[1,3],[2,4],[1,3]]',
    acceptance: '55.4%'
  },
  {
    id: 'max_area_island',
    number: 695,
    title: 'Max Area of Island',
    difficulty: 'Medium',
    category: 'Graphs',
    neetcodeSection: 'Graphs',
    description: 'You are given an m x n binary matrix grid. An island is a group of 1s (representing land) connected 4-directionally. Return the maximum area of an island.',
    inputExample: 'grid = [[0,0,1,0,0,0,0,1,0,0,0,0,0],...]',
    outputExample: '69',
    acceptance: '71.9%'
  },
  {
    id: 'pacific_atlantic_flow',
    number: 417,
    title: 'Pacific Atlantic Water Flow',
    difficulty: 'Medium',
    category: 'Graphs',
    neetcodeSection: 'Graphs',
    description: 'There is an m x n rectangular island. Rainwater flows down to either Pacific Ocean (left/top) or Atlantic Ocean (right/bottom). Find coordinates that can drain to both.',
    inputExample: 'heights = [[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]',
    outputExample: '[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]',
    acceptance: '54.5%'
  },
  {
    id: 'surrounded_regions',
    number: 130,
    title: 'Surrounded Regions',
    difficulty: 'Medium',
    category: 'Graphs',
    neetcodeSection: 'Graphs',
    description: 'Given an m x n matrix board containing "X" and "O", capture all regions connected 4-directionally that are surrounded by "X" by swapping them to "X".',
    inputExample: 'board = [["X","X","X","X"],["X","O","O","X"],["X","X","O","X"],["X","O","X","X"]]',
    outputExample: '[["X","X","X","X"],["X","X","X","X"],["X","X","X","X"],["X","O","X","X"]]',
    acceptance: '38.2%'
  },
  {
    id: 'rotting_oranges',
    number: 994,
    title: 'Rotting Oranges',
    difficulty: 'Medium',
    category: 'Graphs',
    neetcodeSection: 'Graphs',
    description: 'You are given an m x n grid where each cell represents an empty, fresh, or rotten orange. Return the minimum cells time until no fresh oranges remain (-1 if impossible).',
    inputExample: 'grid = [[2,1,1],[1,1,0],[0,1,1]]',
    outputExample: '4',
    acceptance: '53.6%'
  },
  {
    id: 'walls_and_gates',
    number: 286,
    title: 'Walls and Gates',
    difficulty: 'Medium',
    category: 'Graphs',
    neetcodeSection: 'Graphs',
    description: 'You are given an m x n grid initialized with: -1 (wall), 0 (gate), INF (empty room). Fill each empty room with the distance to its nearest gate.',
    inputExample: 'rooms = [[2147483647,-1,0,2147483647],...]',
    outputExample: '[[3,-1,0,1],...]',
    acceptance: '61.0%'
  },
  {
    id: 'course_schedule',
    number: 207,
    title: 'Course Schedule',
    difficulty: 'Medium',
    category: 'Graphs',
    neetcodeSection: 'Graphs',
    description: 'There are a total of numCourses courses you have to take, labeled from 0 to numCourses - 1. You are given prerequisites. Return true if you can finish all courses.',
    inputExample: 'numCourses = 2, prerequisites = [[1,0]]',
    outputExample: 'true',
    acceptance: '46.1%'
  },
  {
    id: 'course_schedule_ii',
    number: 210,
    title: 'Course Schedule II',
    difficulty: 'Medium',
    category: 'Graphs',
    neetcodeSection: 'Graphs',
    description: 'Return the ordering of courses you should take to finish all courses (0 to numCourses-1) based on prerequisites. Return empty array if impossible.',
    inputExample: 'numCourses = 4, prerequisites = [[1,0],[2,0],[3,1],[3,2]]',
    outputExample: '[0,1,2,3]',
    acceptance: '49.8%'
  },
  {
    id: 'redundant_connection',
    number: 684,
    title: 'Redundant Connection',
    difficulty: 'Medium',
    category: 'Graphs',
    neetcodeSection: 'Graphs',
    description: 'In this problem, a tree is an undirected graph that is connected and has no cycles. Return an edge that can be removed so that the resulting graph is a tree of n nodes.',
    inputExample: 'edges = [[1,2],[1,3],[2,3]]',
    outputExample: '[2, 3]',
    acceptance: '62.7%'
  },
  {
    id: 'connected_components_undirected',
    number: 323,
    title: 'Number of Connected Components in Graph',
    difficulty: 'Medium',
    category: 'Graphs',
    neetcodeSection: 'Graphs',
    description: 'Given n nodes in an undirected graph and a list of edges, return the total count of distinct isolated connected components.',
    inputExample: 'n = 5, edges = [[0,1],[1,2],[3,4]]',
    outputExample: '2',
    acceptance: '62.0%'
  },
  {
    id: 'graph_valid_tree',
    number: 261,
    title: 'Graph Valid Tree',
    difficulty: 'Medium',
    category: 'Graphs',
    neetcodeSection: 'Graphs',
    description: 'Given n nodes labeled from 0 to n-1 and a list of undirected edges, write a function to check whether these edges make up a valid tree (fully connected & acyclic).',
    inputExample: 'n = 5, edges = [[0,1],[0,2],[0,3],[1,4]]',
    outputExample: 'true',
    acceptance: '47.5%'
  },
  {
    id: 'word_ladder',
    number: 127,
    title: 'Word Ladder',
    difficulty: 'Hard',
    category: 'Graphs',
    neetcodeSection: 'Graphs',
    description: 'A transformation sequence of word beginWord to endWord using a dictionary. Return the length of the shortest transformation sequence.',
    inputExample: 'beginWord = "hit", endWord = "cog", wordList = ["hot","dot","dog","lot","log","cog"]',
    outputExample: '5',
    acceptance: '38.6%'
  },

  // ==================== ADVANCED GRAPHS (6/6) ====================
  {
    id: 'reconstruct_itinerary',
    number: 332,
    title: 'Reconstruct Itinerary',
    difficulty: 'Hard',
    category: 'Advanced Graphs',
    neetcodeSection: 'Advanced Graphs',
    description: 'You are given a list of airline tickets where tickets[i] = [from, to]. Reconstruct the itinerary in order and return it, minimizing lexical ordering on ties.',
    inputExample: 'tickets = [["MUC","LHR"],["JFK","MUC"],["SFO","SJC"],["LHR","SFO"]]',
    outputExample: '["JFK","MUC","LHR","SFO","SJC"]',
    acceptance: '42.6%'
  },
  {
    id: 'min_cost_connect_points',
    number: 1584,
    title: 'Min Cost to Connect All Points',
    difficulty: 'Medium',
    category: 'Advanced Graphs',
    neetcodeSection: 'Advanced Graphs',
    description: 'You are given an array points representing integer coordinates on a 2D-plane. Return the minimum cost to make all points connected (Minimum Spanning Tree).',
    inputExample: 'points = [[0,0],[2,2],[3,10],[5,2],[7,0]]',
    outputExample: '20',
    acceptance: '64.9%'
  },
  {
    id: 'network_delay_time',
    number: 743,
    title: 'Network Delay Time',
    difficulty: 'Medium',
    category: 'Advanced Graphs',
    neetcodeSection: 'Advanced Graphs',
    description: 'You are given a network of n nodes, labeled 1 to n, and a list of travel times. Signal starts at node k. Return the minimum time for all nodes to receive it.',
    inputExample: 'times = [[2,1,1],[2,3,1],[3,4,1]], n = 4, k = 2',
    outputExample: '2',
    acceptance: '53.1%'
  },
  {
    id: 'swim_rising_water',
    number: 778,
    title: 'Swim in Rising Water',
    difficulty: 'Hard',
    category: 'Advanced Graphs',
    neetcodeSection: 'Advanced Graphs',
    description: 'On an n x n grid grid, each square represents elevation. Rain falls starting at t=0, and you can swim between adjacent grid cells when water height matches.',
    inputExample: 'grid = [[0,2],[1,3]]',
    outputExample: '3',
    acceptance: '61.4%'
  },
  {
    id: 'alien_dictionary',
    number: 269,
    title: 'Alien Dictionary',
    difficulty: 'Hard',
    category: 'Advanced Graphs',
    neetcodeSection: 'Advanced Graphs',
    description: 'There is a new alien language that uses the English alphabet. Given a list of words sorted lexicographically by the alien rules, find the symbol sorting order.',
    inputExample: 'words = ["wrt","wrf","er","ett","rftt"]',
    outputExample: '"wertf"',
    acceptance: '35.6%'
  },
  {
    id: 'cheapest_flights_k_stops',
    number: 787,
    title: 'Cheapest Flights Within K Stops',
    difficulty: 'Medium',
    category: 'Advanced Graphs',
    neetcodeSection: 'Advanced Graphs',
    description: 'There are n cities connected by some number of flights. Find the cheapest price from src to dst with at most k stops; return -1 if impossible.',
    inputExample: 'n = 4, flights = [[0,1,100],[1,2,100],[2,0,100],[1,3,600],[2,3,200]], src = 0, dst = 3, k = 1',
    outputExample: '700',
    acceptance: '38.5%'
  },

  // ==================== 1-D DP (12/12) ====================
  {
    id: 'climbing_stairs',
    number: 70,
    title: 'Climbing Stairs',
    difficulty: 'Easy',
    category: '1-D DP',
    neetcodeSection: '1-D DP',
    description: 'You are climbing a staircase. It takes n steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?',
    inputExample: 'n = 3',
    outputExample: '3',
    acceptance: '52.7%'
  },
  {
    id: 'min_cost_climbing_stairs',
    number: 746,
    title: 'Min Cost Climbing Stairs',
    difficulty: 'Easy',
    category: '1-D DP',
    neetcodeSection: '1-D DP',
    description: 'You are given an integer array cost where cost[i] is the cost of i-th step on a staircase. Once you pay the cost, you can climb one or two steps.',
    inputExample: 'cost = [10,15,20]',
    outputExample: '15',
    acceptance: '64.9%'
  },
  {
    id: 'house_robber',
    number: 198,
    title: 'House Robber',
    difficulty: 'Medium',
    category: '1-D DP',
    neetcodeSection: '1-D DP',
    description: 'You are a professional robber planning to rob houses along a street. Each house has a stash of money. You cannot rob adjacent houses. Maximize your loot.',
    inputExample: 'nums = [1,2,3,1]',
    outputExample: '4',
    acceptance: '50.2%'
  },
  {
    id: 'house_robber_ii',
    number: 213,
    title: 'House Robber II',
    difficulty: 'Medium',
    category: '1-D DP',
    neetcodeSection: '1-D DP',
    description: 'Rob houses situated in a circle (first house is adjacent to the last house). Return the maximum amount of money you can rob without alerting police.',
    inputExample: 'nums = [2,3,2]',
    outputExample: '3',
    acceptance: '41.6%'
  },
  {
    id: 'longest_palindrome_substring',
    number: 5,
    title: 'Longest Palindromic Substring',
    difficulty: 'Medium',
    category: '1-D DP',
    neetcodeSection: '1-D DP',
    description: 'Given a string s, return the longest palindromic substring in s.',
    inputExample: 's = "babad"',
    outputExample: '"bab"',
    acceptance: '33.2%'
  },
  {
    id: 'palindromic_substrings',
    number: 647,
    title: 'Palindromic Substrings',
    difficulty: 'Medium',
    category: '1-D DP',
    neetcodeSection: '1-D DP',
    description: 'Given a string s, return the number of palindromic substrings in s, counting duplicates.',
    inputExample: 's = "aaa"',
    outputExample: '6',
    acceptance: '67.4%'
  },
  {
    id: 'decode_ways',
    number: 91,
    title: 'Decode Ways',
    difficulty: 'Medium',
    category: '1-D DP',
    neetcodeSection: '1-D DP',
    description: 'A message containing letters from A-Z can be encoded into numbers. Determine the total number of ways to decode an integer string.',
    inputExample: 's = "226"',
    outputExample: '3 (combos: "BZ", "VF", "BBF")',
    acceptance: '34.8%'
  },
  {
    id: 'coin_change',
    number: 322,
    title: 'Coin Change',
    difficulty: 'Medium',
    category: '1-D DP',
    neetcodeSection: '1-D DP',
    description: 'Given coins of different denominations and a total amount. Compute fewest coins to make up that amount (-1 if impossible).',
    inputExample: 'coins = [1,2,5], amount = 11',
    outputExample: '3',
    acceptance: '43.2%'
  },
  {
    id: 'max_product_subarray',
    number: 152,
    title: 'Maximum Product Subarray',
    difficulty: 'Medium',
    category: '1-D DP',
    neetcodeSection: '1-D DP',
    description: 'Given an integer array nums, find a contiguous non-empty subarray within the array that has the largest product, and return the product.',
    inputExample: 'nums = [2,3,-2,4]',
    outputExample: '6',
    acceptance: '35.4%'
  },
  {
    id: 'word_break',
    number: 139,
    title: 'Word Break',
    difficulty: 'Medium',
    category: '1-D DP',
    neetcodeSection: '1-D DP',
    description: 'Given a string s and a dictionary of strings wordDict, return true if s can be segmented into a space-separated sequence of one or more dictionary words.',
    inputExample: 's = "applepenapple", wordDict = ["apple","pen"]',
    outputExample: 'true',
    acceptance: '46.7%'
  },
  {
    id: 'longest_increasing_subsequence',
    number: 300,
    title: 'Longest Increasing Subsequence',
    difficulty: 'Medium',
    category: '1-D DP',
    neetcodeSection: '1-D DP',
    description: 'Given an integer array nums, return the length of the longest strictly increasing subsequence in O(n log n) time.',
    inputExample: 'nums = [10,9,2,5,3,7,101,18]',
    outputExample: '4',
    acceptance: '53.1%'
  },
  {
    id: 'partition_equal_subset_sum',
    number: 416,
    title: 'Partition Equal Subset Sum',
    difficulty: 'Medium',
    category: '1-D DP',
    neetcodeSection: '1-D DP',
    description: 'Given an integer array nums, return true if you can partition the array into two subsets such that the sum of the elements in both subsets is equal.',
    inputExample: 'nums = [1,5,11,5]',
    outputExample: 'true',
    acceptance: '46.3%'
  },

  // ==================== 2-D DP (11/11) ====================
  {
    id: 'unique_paths',
    number: 62,
    title: 'Unique Paths',
    difficulty: 'Medium',
    category: '2-D DP',
    neetcodeSection: '2-D DP',
    description: 'There is a robot on an m x n grid, starting at top-left. The robot can only move down or right. Robot wants to reach bottom-right. How many unique paths exist?',
    inputExample: 'm = 3, n = 7',
    outputExample: '28',
    acceptance: '64.1%'
  },
  {
    id: 'longest_common_subsequence',
    number: 1143,
    title: 'Longest Common Subsequence',
    difficulty: 'Medium',
    category: '2-D DP',
    neetcodeSection: '2-D DP',
    description: 'Given two strings text1 and text2, return the length of their longest common subsequence. A subsequence is distinct from a substring.',
    inputExample: 'text1 = "abcde", text2 = "ace"',
    outputExample: '3',
    acceptance: '51.8%'
  },
  {
    id: 'buy_sell_stock_cooldown',
    number: 309,
    title: 'Best Time to Buy and Sell Stock with Cooldown',
    difficulty: 'Medium',
    category: '2-D DP',
    neetcodeSection: '2-D DP',
    description: 'Find max profit from stocking transactions with rules: you cannot buy immediately after selling a stock (1 day cooldown cooldown).',
    inputExample: 'prices = [1,2,3,0,2]',
    outputExample: '3',
    acceptance: '57.4%'
  },
  {
    id: 'coin_change_ii',
    number: 518,
    title: 'Coin Change II',
    difficulty: 'Medium',
    category: '2-D DP',
    neetcodeSection: '2-D DP',
    description: 'Given coins of different denominations and a total amount. Compute amount of combinations to make up that sum.',
    inputExample: 'amount = 5, coins = [1,2,5]',
    outputExample: '4',
    acceptance: '62.8%'
  },
  {
    id: 'target_sum',
    number: 494,
    title: 'Target Sum',
    difficulty: 'Medium',
    category: '2-D DP',
    neetcodeSection: '2-D DP',
    description: 'You are given an integer array nums and an integer target. Build an expression using operations "+" and "-" before each element to equal target.',
    inputExample: 'nums = [1,1,1,1,1], target = 3',
    outputExample: '5',
    acceptance: '46.7%'
  },
  {
    id: 'interleaving_string',
    number: 97,
    title: 'Interleaving String',
    difficulty: 'Medium',
    category: '2-D DP',
    neetcodeSection: '2-D DP',
    description: 'Given strings s1, s2, and s3, find whether s3 is formed by an interleaving of s1 and s2.',
    inputExample: 's1 = "aabcc", s2 = "dbbca", s3 = "aadbbcbcac"',
    outputExample: 'true',
    acceptance: '38.6%'
  },
  {
    id: 'longest_increasing_path',
    number: 329,
    title: 'Longest Increasing Path in a Matrix',
    difficulty: 'Hard',
    category: '2-D DP',
    neetcodeSection: '2-D DP',
    description: 'Given an m x n integers matrix, return the length of the longest increasing path in matrix, traveling 4-directionally.',
    inputExample: 'matrix = [[9,9,4],[6,6,8],[2,1,1]]',
    outputExample: '4',
    acceptance: '53.1%'
  },
  {
    id: 'distinct_subsequences',
    number: 115,
    title: 'Distinct Subsequences',
    difficulty: 'Hard',
    category: '2-D DP',
    neetcodeSection: '2-D DP',
    description: 'Given two strings s and t, return the number of distinct subsequences of s which equals t.',
    inputExample: 's = "rabbbit", t = "rabbit"',
    outputExample: '3',
    acceptance: '45.8%'
  },
  {
    id: 'edit_distance',
    number: 72,
    title: 'Edit Distance',
    difficulty: 'Hard',
    category: '2-D DP',
    neetcodeSection: '2-D DP',
    description: 'Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2 (insert, delete, replace).',
    inputExample: 'word1 = "horse", word2 = "ros"',
    outputExample: '3',
    acceptance: '54.5%'
  },
  {
    id: 'burst_balloons',
    number: 312,
    title: 'Burst Balloons',
    difficulty: 'Hard',
    category: '2-D DP',
    neetcodeSection: '2-D DP',
    description: 'You are given n balloons, indexed 0 to n-1. Bursting balloon i earns nums[i-1] * nums[i] * nums[i+1] coins. Maximize total coins.',
    inputExample: 'nums = [3,1,5,8]',
    outputExample: '167',
    acceptance: '57.4%'
  },
  {
    id: 'regular_expression_matching',
    number: 10,
    title: 'Regular Expression Matching',
    difficulty: 'Hard',
    category: '2-D DP',
    neetcodeSection: '2-D DP',
    description: 'Given an input string s and a pattern p, implement regular expression matching with support for "." and "*" wildcard operators.',
    inputExample: 's = "aa", p = "a*"',
    outputExample: 'true',
    acceptance: '28.5%'
  },

  // ==================== GREEDY (8/8) ====================
  {
    id: 'maximum_subarray',
    number: 53,
    title: 'Maximum Subarray',
    difficulty: 'Medium',
    category: 'Greedy',
    neetcodeSection: 'Greedy',
    description: 'Given an integer array nums, find the contiguous subarray (containing at least one number) which has the largest sum and return its sum.',
    inputExample: 'nums = [-2,1,-3,4,-1,2,1,-5,4]',
    outputExample: '6',
    acceptance: '50.3%'
  },
  {
    id: 'jump_game',
    number: 55,
    title: 'Jump Game',
    difficulty: 'Medium',
    category: 'Greedy',
    neetcodeSection: 'Greedy',
    description: 'You are given an integer array nums. You are initially positioned at the array\'s first index. Determine if you are able to reach the last index.',
    inputExample: 'nums = [2,3,1,1,4]',
    outputExample: 'true',
    acceptance: '38.5%'
  },
  {
    id: 'jump_game_ii',
    number: 45,
    title: 'Jump Game II',
    difficulty: 'Medium',
    category: 'Greedy',
    neetcodeSection: 'Greedy',
    description: 'Given an array of non-negative integers nums, you are initially positioned at the first index. Find minimum jumps to reach last index.',
    inputExample: 'nums = [2,3,1,1,4]',
    outputExample: '2',
    acceptance: '44.8%'
  },
  {
    id: 'gas_station',
    number: 134,
    title: 'Gas Station',
    difficulty: 'Medium',
    category: 'Greedy',
    neetcodeSection: 'Greedy',
    description: 'There are n gas stations along a circular route. Given gas and cost cost. Return the starting gas station\'s index if you can travel around the circuit once.',
    inputExample: 'gas = [1,2,3,4,5], cost = [3,4,5,1,2]',
    outputExample: '3',
    acceptance: '45.1%'
  },
  {
    id: 'hand_of_straights',
    number: 846,
    title: 'Hand of Straights',
    difficulty: 'Medium',
    category: 'Greedy',
    neetcodeSection: 'Greedy',
    description: 'Alice has some cards. Rearrange cards into groups of groupSize where each group is consecutive straight cards.',
    inputExample: 'hand = [1,2,3,6,2,3,4,7,8], groupSize = 3',
    outputExample: 'true',
    acceptance: '56.9%'
  },
  {
    id: 'merge_triplets_target',
    number: 1899,
    title: 'Merge Triplets to Form Target Triplet',
    difficulty: 'Medium',
    category: 'Greedy',
    neetcodeSection: 'Greedy',
    description: 'Given a 2D integer array triplets and target. Update a triplet using max operations to see if you can form the target triplet.',
    inputExample: 'triplets = [[2,5,3],[1,8,4]], target = [1,7,5]',
    outputExample: 'false',
    acceptance: '67.4%'
  },
  {
    id: 'partition_labels',
    number: 763,
    title: 'Partition Labels',
    difficulty: 'Medium',
    category: 'Greedy',
    neetcodeSection: 'Greedy',
    description: 'You are given a string s. Partition s into as many parts as possible so that each letter appears in at most one part.',
    inputExample: 's = "ababcbacadefegdehijhklij"',
    outputExample: '[9,7,8]',
    acceptance: '79.6%'
  },
  {
    id: 'valid_parenthesis_string',
    number: 678,
    title: 'Valid Parenthesis String',
    difficulty: 'Medium',
    category: 'Greedy',
    neetcodeSection: 'Greedy',
    description: 'Given a string containing only brackets and asterisks "*", where asterisks can be empty, left parenthesis, or right parenthesis. Check if string is valid.',
    inputExample: 's = "(*)"',
    outputExample: 'true',
    acceptance: '35.1%'
  },

  // ==================== INTERVALS (6/6) ====================
  {
    id: 'insert_interval',
    number: 57,
    title: 'Insert Interval',
    difficulty: 'Medium',
    category: 'Intervals',
    neetcodeSection: 'Intervals',
    description: 'You are given an array of non-overlapping intervals sorted by start. Insert a newInterval and merge overlapping intervals.',
    inputExample: 'intervals = [[1,3],[6,9]], newInterval = [2,5]',
    outputExample: '[[1,5],[6,9]]',
    acceptance: '41.3%'
  },
  {
    id: 'merge_intervals',
    number: 56,
    title: 'Merge Intervals',
    difficulty: 'Medium',
    category: 'Intervals',
    neetcodeSection: 'Intervals',
    description: 'Given an array of intervals, merge all overlapping intervals, and return an array of the non-overlapping intervals.',
    inputExample: 'intervals = [[1,3],[2,6],[8,10],[15,18]]',
    outputExample: '[[1,6],[8,10],[15,18]]',
    acceptance: '46.7%'
  },
  {
    id: 'non_overlapping_intervals',
    number: 435,
    title: 'Non-overlapping Intervals',
    difficulty: 'Medium',
    category: 'Intervals',
    neetcodeSection: 'Intervals',
    description: 'Given an array of intervals, find the minimum number of intervals you need to remove to make the rest of the intervals non-overlapping.',
    inputExample: 'intervals = [[1,2],[2,3],[3,4],[1,3]]',
    outputExample: '1',
    acceptance: '53.1%'
  },
  {
    id: 'meeting_rooms',
    number: 252,
    title: 'Meeting Rooms',
    difficulty: 'Easy',
    category: 'Intervals',
    neetcodeSection: 'Intervals',
    description: 'Given an array of meeting time intervals consisting of start and end times, determine if a person could attend all meetings.',
    inputExample: 'intervals = [[0,30],[5,10],[15,20]]',
    outputExample: 'false',
    acceptance: '57.4%'
  },
  {
    id: 'meeting_rooms_ii',
    number: 253,
    title: 'Meeting Rooms II',
    difficulty: 'Medium',
    category: 'Intervals',
    neetcodeSection: 'Intervals',
    description: 'Given an array of meeting time intervals, find the minimum number of conference rooms required.',
    inputExample: 'intervals = [[0,30],[5,10],[15,20]]',
    outputExample: '2',
    acceptance: '53.2%'
  },
  {
    id: 'min_interval_query',
    number: 1854,
    title: 'Minimum Interval to Include Each Query',
    difficulty: 'Hard',
    category: 'Intervals',
    neetcodeSection: 'Intervals',
    description: 'Given intervals and queries. For each query, find the size of the smallest interval containing it.',
    inputExample: 'intervals = [[1,4],[2,4],[3,6],[4,4]], queries = [2,3,4,5]',
    outputExample: '[3,3,1,4]',
    acceptance: '38.5%'
  },

  // ==================== MATH & GEOMETRY (8/8) ====================
  {
    id: 'rotate_image',
    number: 48,
    title: 'Rotate Image',
    difficulty: 'Medium',
    category: 'Math & Geometry',
    neetcodeSection: 'Math & Geometry',
    description: 'You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees clockwise in-place.',
    inputExample: 'matrix = [[1,2,3],[4,5,6],[7,8,9]]',
    outputExample: '[[7,4,1],[8,5,2],[9,6,3]]',
    acceptance: '71.5%'
  },
  {
    id: 'spiral_matrix',
    number: 54,
    title: 'Spiral Matrix',
    difficulty: 'Medium',
    category: 'Math & Geometry',
    neetcodeSection: 'Math & Geometry',
    description: 'Given an m x n matrix, return all elements of the matrix in spiral order.',
    inputExample: 'matrix = [[1,2,3],[4,5,6],[7,8,9]]',
    outputExample: '[1,2,3,6,9,8,7,4,5]',
    acceptance: '49.2%'
  },
  {
    id: 'set_matrix_zeroes',
    number: 73,
    title: 'Set Matrix Zeroes',
    difficulty: 'Medium',
    category: 'Math & Geometry',
    neetcodeSection: 'Math & Geometry',
    description: 'Given an m x n integer matrix matrix, if an element is 0, set its entire row and column to 0 in-place.',
    inputExample: 'matrix = [[1,1,1],[1,0,1],[1,1,1]]',
    outputExample: '[[1,0,1],[0,0,0],[1,0,1]]',
    acceptance: '53.6%'
  },
  {
    id: 'happy_number',
    number: 202,
    title: 'Happy Number',
    difficulty: 'Easy',
    category: 'Math & Geometry',
    neetcodeSection: 'Math & Geometry',
    description: 'Write an algorithm to determine if a number n is happy, where squaring digit sums repeatedly winds up at 1.',
    inputExample: 'n = 19',
    outputExample: 'true',
    acceptance: '46.8%'
  },
  {
    id: 'plus_one',
    number: 66,
    title: 'Plus One',
    difficulty: 'Easy',
    category: 'Math & Geometry',
    neetcodeSection: 'Math & Geometry',
    description: 'You are given a large integer represented as an integer array digits, where each digits[i] is the i-th digit. Increment the integer by one.',
    inputExample: 'digits = [1,2,3]',
    outputExample: '[1,2,4]',
    acceptance: '44.3%'
  },
  {
    id: 'pow_x_n',
    number: 50,
    title: 'Pow(x, n)',
    difficulty: 'Medium',
    category: 'Math & Geometry',
    neetcodeSection: 'Math & Geometry',
    description: 'Implement pow(x, n), which calculates x raised to the power n.',
    inputExample: 'x = 2.00000, n = 10',
    outputExample: '1024.00000',
    acceptance: '34.5%'
  },
  {
    id: 'multiply_strings',
    number: 43,
    title: 'Multiply Strings',
    difficulty: 'Medium',
    category: 'Math & Geometry',
    neetcodeSection: 'Math & Geometry',
    description: 'Given two non-negative integers num1 and num2 represented as strings, return the product of num1 and num2, also represented as a string.',
    inputExample: 'num1 = "2", num2 = "3"',
    outputExample: '"6"',
    acceptance: '39.8%'
  },
  {
    id: 'detect_squares',
    number: 2013,
    title: 'Detect Squares',
    difficulty: 'Medium',
    category: 'Math & Geometry',
    neetcodeSection: 'Math & Geometry',
    description: 'Design a data structure to detect squares in a stream of 2D coordinates dynamically.',
    inputExample: '["DetectSquares","add","add","add","count"]',
    outputExample: '[null,null,null,null,1]',
    acceptance: '51.3%'
  },

  // ==================== BIT MANIPULATION (7/7) ====================
  {
    id: 'single_number',
    number: 136,
    title: 'Single Number',
    difficulty: 'Easy',
    category: 'Bit Manipulation',
    neetcodeSection: 'Bit Manipulation',
    description: 'Given a non-empty array of integers nums, every element appears twice except for one. Find that single one in linear runtime and O(1) space.',
    inputExample: 'nums = [2,2,1]',
    outputExample: '1',
    acceptance: '71.5%'
  },
  {
    id: 'number_of_1_bits',
    number: 191,
    title: 'Number of 1 Bits',
    difficulty: 'Easy',
    category: 'Bit Manipulation',
    neetcodeSection: 'Bit Manipulation',
    description: 'Write a function that takes the binary representation of an unsigned integer and returns the number of \'1\' bits (also known as Hamming weight).',
    inputExample: 'n = 11 (binary: 1011)',
    outputExample: '3',
    acceptance: '66.2%'
  },
  {
    id: 'counting_bits',
    number: 338,
    title: 'Counting Bits',
    difficulty: 'Easy',
    category: 'Bit Manipulation',
    neetcodeSection: 'Bit Manipulation',
    description: 'Given an integer n, return an array ans of length n + 1 such that for each i (0 <= i <= n), ans[i] is the number of 1\'s in the binary representation of i.',
    inputExample: 'n = 5',
    outputExample: '[0,1,1,2,1,2]',
    acceptance: '77.4%'
  },
  {
    id: 'reverse_bits',
    number: 190,
    title: 'Reverse Bits',
    difficulty: 'Easy',
    category: 'Bit Manipulation',
    neetcodeSection: 'Bit Manipulation',
    description: 'Reverse bits of a given 32-bit unsigned integer.',
    inputExample: 'n = 00000010100101000001111010011100',
    outputExample: '964176192 (00111001011110000010100101000000)',
    acceptance: '56.9%'
  },
  {
    id: 'missing_number',
    number: 268,
    title: 'Missing Number',
    difficulty: 'Easy',
    category: 'Bit Manipulation',
    neetcodeSection: 'Bit Manipulation',
    description: 'Given an array nums containing n distinct numbers in the range [0, n], return the only number in the range that is missing from the array.',
    inputExample: 'nums = [3,0,1]',
    outputExample: '2',
    acceptance: '63.0%'
  },
  {
    id: 'sum_two_integers',
    number: 371,
    title: 'Sum of Two Integers',
    difficulty: 'Medium',
    category: 'Bit Manipulation',
    neetcodeSection: 'Bit Manipulation',
    description: 'Given two integers a and b, return the sum of the two integers without using the operators "+" and "-".',
    inputExample: 'a = 1, b = 2',
    outputExample: '3',
    acceptance: '51.2%'
  },
  {
    id: 'reverse_integer_bit',
    number: 7,
    title: 'Reverse Integer',
    difficulty: 'Medium',
    category: 'Bit Manipulation',
    neetcodeSection: 'Bit Manipulation',
    description: 'Given a signed 32-bit integer x, return x with its digits reversed. If reversing x causes the value to go outside the signed 32-bit integer range, then return 0.',
    inputExample: 'x = -123',
    outputExample: '-321',
    acceptance: '28.1%'
  }
];
